DEL "Accounting\bin\Release\*.XML" /s /q
DEL "Accounting\bin\Release\*.pdb" /s /q
DEL "ControllerManagement.Module\bin\Release\*.XML" /s /q
DEL "ControllerManagement.Module\bin\Release\*.pdb" /s /q
DEL "Recruitment.Mobile\bin\Release\*.XML" /s /q
DEL "Recruitment.Mobile\bin\Release\*.pdb" /s /q
DEL "Recruitment.Module\bin\Release\*.XML" /s /q
DEL "Recruitment.Module\bin\Release\*.pdb" /s /q
DEL "Recruitment.Module.Mobile\bin\Release\*.XML" /s /q
DEL "Recruitment.Module.Mobile\bin\Release\*.pdb" /s /q
DEL "Recruitment.Module.Web\bin\Release\*.XML" /s /q
DEL "Recruitment.Module.Web\bin\Release\*.pdb" /s /q
DEL "Recruitment.Module.Win\bin\Release\*.XML" /s /q
DEL "Recruitment.Module.Win\bin\Release\*.pdb" /s /q
DEL "Recruitment.Web\bin\Release\*.XML" /s /q
DEL "Recruitment.Web\bin\Release\*.pdb" /s /q
DEL "Recruitment.Win\bin\Release\*.XML" /s /q
DEL "Recruitment.Win\bin\Release\*.pdb" /s /q
