RMDIR "Accounting\bin" /s /q
RMDIR "Accounting\obj" /s /q
RMDIR "ControllerManagement.Module\bin" /s /q
RMDIR "ControllerManagement.Module\obj" /s /q
RMDIR "Recruitment.Mobile\bin" /s /q
RMDIR "Recruitment.Mobile\obj" /s /q
RMDIR "Recruitment.Module\bin" /s /q
RMDIR "Recruitment.Module\obj" /s /q
RMDIR "Recruitment.Module.Mobile\bin" /s /q
RMDIR "Recruitment.Module.Mobile\obj" /s /q
RMDIR "Recruitment.Module.Web\bin" /s /q
RMDIR "Recruitment.Module.Web\obj" /s /q
RMDIR "Recruitment.Module.Win\bin" /s /q
RMDIR "Recruitment.Module.Win\obj" /s /q
RMDIR "Recruitment.Web\bin" /s /q
RMDIR "Recruitment.Web\obj" /s /q
RMDIR "Recruitment.Win\bin" /s /q
RMDIR "Recruitment.Win\obj" /s /q