//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class acc_Account_Applicant : XPLiteObject
    {
        int facc_account_id_applicant_id;
        [Key(true)]
        public int acc_account_id_applicant_id
        {
            get { return facc_account_id_applicant_id; }
            set { SetPropertyValue<int>("acc_account_id_applicant_id", ref facc_account_id_applicant_id, value); }
        }
        rec_Employer_Order_Detail_Accept_Applicat frec_employer_order_detail_accept_applicat_rec_employer_order_detail_suggest_applicat_id;
        [Association(@"acc_Account_ApplicantReferencesrec_Employer_Order_Detail_Accept_Applicat")]
        public rec_Employer_Order_Detail_Accept_Applicat rec_employer_order_detail_accept_applicat_rec_employer_order_detail_suggest_applicat_id
        {
            get { return frec_employer_order_detail_accept_applicat_rec_employer_order_detail_suggest_applicat_id; }
            set { SetPropertyValue<rec_Employer_Order_Detail_Accept_Applicat>("rec_employer_order_detail_accept_applicat_rec_employer_order_detail_suggest_applicat_id", ref frec_employer_order_detail_accept_applicat_rec_employer_order_detail_suggest_applicat_id, value); }
        }
        int faccount_id;
        [Indexed(Name = @"iaccount_id_acc_Account_Applicant")]
        public int account_id
        {
            get { return faccount_id; }
            set { SetPropertyValue<int>("account_id", ref faccount_id, value); }
        }
    }

}
