//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Employer_Order_Detail : XPLiteObject
    {
        int frec_employer_order_detail_id;
        [Key(true)]
        public int rec_employer_order_detail_id
        {
            get { return frec_employer_order_detail_id; }
            set { SetPropertyValue<int>("rec_employer_order_detail_id", ref frec_employer_order_detail_id, value); }
        }
        rec_Employer_Order frec_employer_order_detail_rec_employer_order_id;
        [Indexed(Name = @"irec_employer_order_detail_rec_employer_order_id_rec_Employer_Order_Detail")]
        [Association(@"rec_Employer_Order_DetailReferencesrec_Employer_Order")]
        public rec_Employer_Order rec_employer_order_detail_rec_employer_order_id
        {
            get { return frec_employer_order_detail_rec_employer_order_id; }
            set { SetPropertyValue<rec_Employer_Order>("rec_employer_order_detail_rec_employer_order_id", ref frec_employer_order_detail_rec_employer_order_id, value); }
        }
        rec_Industry frec_employer_order_detail_industry_id;
        [Indexed(Name = @"irec_employer_order_detail_industry_id_rec_Employer_Order_Detail")]
        [Association(@"rec_Employer_Order_DetailReferencesrec_Industry")]
        public rec_Industry rec_employer_order_detail_industry_id
        {
            get { return frec_employer_order_detail_industry_id; }
            set { SetPropertyValue<rec_Industry>("rec_employer_order_detail_industry_id", ref frec_employer_order_detail_industry_id, value); }
        }
        int frec_employer_order_detail_count;
        public int rec_employer_order_detail_count
        {
            get { return frec_employer_order_detail_count; }
            set { SetPropertyValue<int>("rec_employer_order_detail_count", ref frec_employer_order_detail_count, value); }
        }
        [Association(@"rec_Employer_Order_Detail_CallReferencesrec_Employer_Order_Detail")]
        public XPCollection<rec_Employer_Order_Detail_Call> rec_Employer_Order_Detail_Calls { get { return GetCollection<rec_Employer_Order_Detail_Call>("rec_Employer_Order_Detail_Calls"); } }
        [Association(@"rec_Employer_Order_Detail_Suggest_ApplicatReferencesrec_Employer_Order_Detail")]
        public XPCollection<rec_Employer_Order_Detail_Suggest_Applicat> rec_Employer_Order_Detail_Suggest_Applicats { get { return GetCollection<rec_Employer_Order_Detail_Suggest_Applicat>("rec_Employer_Order_Detail_Suggest_Applicats"); } }
    }

}
