//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_DocSrv_Order_Detail_Srv : XPLiteObject
    {
        int fdocsrv_order_detail_srv_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int docsrv_order_detail_srv_id
        {
            get { return fdocsrv_order_detail_srv_id; }
            set { SetPropertyValue<int>("docsrv_order_detail_srv_id", ref fdocsrv_order_detail_srv_id, value); }
        }
        rec_DocSrv_Order_Detail fdocsrv_order_detail;
        [Indexed(Name = @"idocsrv_order_detail_rec_DocSrv_Order_Detail_Srv")]
        [Association(@"rec_DocSrv_Order_Detail_SrvReferencesrec_DocSrv_Order_Detail")]
        [DevExpress.Xpo.DisplayName(@"Document Service Order Detail")]
        public rec_DocSrv_Order_Detail docsrv_order_detail
        {
            get { return fdocsrv_order_detail; }
            set { SetPropertyValue<rec_DocSrv_Order_Detail>("docsrv_order_detail", ref fdocsrv_order_detail, value); }
        }
        rec_DocSrv_Type fdocsrv_type_id;
        [Indexed(Name = @"idocsrv_type_id_rec_DocSrv_Order_Detail_Srv")]
        [Association(@"rec_DocSrv_Order_Detail_SrvReferencesrec_DocSrv_Type")]
        [DevExpress.Xpo.DisplayName(@"Service Type")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_DocSrv_Type_docsrv_type_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Select Service Type")]
        public rec_DocSrv_Type docsrv_type_id
        {
            get { return fdocsrv_type_id; }
            set { SetPropertyValue<rec_DocSrv_Type>("docsrv_type_id", ref fdocsrv_type_id, value); }
        }
        DateTime fcompletion_date;
        [DevExpress.Xpo.DisplayName(@"Completion Date")]
        public DateTime completion_date
        {
            get { return fcompletion_date; }
            set { SetPropertyValue<DateTime>("completion_date", ref fcompletion_date, value); }
        }
        string fnotes;
        [Size(1000)]
        [DevExpress.Xpo.DisplayName(@"Notes")]
        public string notes
        {
            get { return fnotes; }
            set { SetPropertyValue<string>("notes", ref fnotes, value); }
        }
        double fprice;
        [DevExpress.Xpo.DisplayName(@"Price")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_DocSrv_Type_price_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Price")]
        public double price
        {
            get { return fprice; }
            set { SetPropertyValue<double>("price", ref fprice, value); }
        }
        bool fpaid;
        [DevExpress.Xpo.DisplayName(@"Paid")]
        public bool paid
        {
            get { return fpaid; }
            set { SetPropertyValue<bool>("paid", ref fpaid, value); }
        }
        bool fis_completed;
        [DevExpress.Xpo.DisplayName(@"Completed")]
        public bool is_completed
        {
            get { return fis_completed; }
            set { SetPropertyValue<bool>("is_completed", ref fis_completed, value); }
        }
        Accounting.BusinessObjects.Recruitment.acc_Journal_Entry fjour_entry_id;
        [Indexed(Name = @"ijour_entry_id_rec_DocSrv_Order_Detail_Srv")]
        [DevExpress.Xpo.DisplayName(@"Revenue Entry")]
        public Accounting.BusinessObjects.Recruitment.acc_Journal_Entry jour_entry_id
        {
            get { return fjour_entry_id; }
            set { SetPropertyValue<Accounting.BusinessObjects.Recruitment.acc_Journal_Entry>("jour_entry_id", ref fjour_entry_id, value); }
        }
        Accounting.BusinessObjects.Recruitment.acc_Journal_Entry fjour_entry_id_Paid;
        [Indexed(Name = @"ijour_entry_id_Paid_rec_DocSrv_Order_Detail_Srv")]
        [DevExpress.Xpo.DisplayName(@"Paid Entry")]
        public Accounting.BusinessObjects.Recruitment.acc_Journal_Entry jour_entry_id_Paid
        {
            get { return fjour_entry_id_Paid; }
            set { SetPropertyValue<Accounting.BusinessObjects.Recruitment.acc_Journal_Entry>("jour_entry_id_Paid", ref fjour_entry_id_Paid, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Document Service Activities")]
        [Association(@"rec_DocSrv_ActivityReferencesrec_DocSrv_Order_Detail_Srv")]
        public XPCollection<rec_DocSrv_Activity> rec_DocSrv_Activitys { get { return GetCollection<rec_DocSrv_Activity>("rec_DocSrv_Activitys"); } }
    }

}
