//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Industry : XPLiteObject
    {
        int findustry_id;
        [Key(true)]
        public int industry_id
        {
            get { return findustry_id; }
            set { SetPropertyValue<int>("industry_id", ref findustry_id, value); }
        }
        string findustry_name;
        public string industry_name
        {
            get { return findustry_name; }
            set { SetPropertyValue<string>("industry_name", ref findustry_name, value); }
        }
        [Association(@"rec_ApplicantReferencesrec_Industry")]
        public XPCollection<rec_Applicant> rec_Applicants { get { return GetCollection<rec_Applicant>("rec_Applicants"); } }
        [Association(@"rec_Applicant_EducationReferencesrec_Industry")]
        public XPCollection<rec_Applicant_Education> rec_Applicant_Educations { get { return GetCollection<rec_Applicant_Education>("rec_Applicant_Educations"); } }
        [Association(@"rec_Applicant_ExperienceReferencesrec_Industry")]
        public XPCollection<rec_Applicant_Experience> rec_Applicant_Experiences { get { return GetCollection<rec_Applicant_Experience>("rec_Applicant_Experiences"); } }
        [Association(@"rec_Employer_Order_DetailReferencesrec_Industry")]
        public XPCollection<rec_Employer_Order_Detail> rec_Employer_Order_Details { get { return GetCollection<rec_Employer_Order_Detail>("rec_Employer_Order_Details"); } }
        [Association(@"rec_Industry_Require_Doc_InfoReferencesrec_Industry")]
        public XPCollection<rec_Industry_Require_Doc_Info> rec_Industry_Require_Doc_Infos { get { return GetCollection<rec_Industry_Require_Doc_Info>("rec_Industry_Require_Doc_Infos"); } }
        [Association(@"rec_Employer_IndustryReferencesrec_Industry")]
        public XPCollection<rec_Employer_Industry> rec_Employer_Industrys { get { return GetCollection<rec_Employer_Industry>("rec_Employer_Industrys"); } }
    }

}
