//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Employee : XPLiteObject
    {
        int femployee_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int employee_id
        {
            get { return femployee_id; }
            set { SetPropertyValue<int>("employee_id", ref femployee_id, value); }
        }
        string femployee_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Employee name")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_Employee_employee_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Name")]
        public string employee_name
        {
            get { return femployee_name; }
            set { SetPropertyValue<string>("employee_name", ref femployee_name, value); }
        }
        string fjob_title;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Job title")]
        public string job_title
        {
            get { return fjob_title; }
            set { SetPropertyValue<string>("job_title", ref fjob_title, value); }
        }
        double fsalary;
        [DevExpress.Xpo.DisplayName(@"Salary")]
        public double salary
        {
            get { return fsalary; }
            set { SetPropertyValue<double>("salary", ref fsalary, value); }
        }
        bool factive;
        [DevExpress.Xpo.DisplayName(@"Active")]
        public bool active
        {
            get { return factive; }
            set { SetPropertyValue<bool>("active", ref factive, value); }
        }
        [Association(@"rec_Employee_ActivityReferencesrec_Employee")]
        public XPCollection<rec_Employee_Activity> rec_Employee_Activitys { get { return GetCollection<rec_Employee_Activity>("rec_Employee_Activitys"); } }
    }

}
