//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Employer_Order : XPLiteObject
    {
        int frec_employer_order_id;
        [Key(true)]
        public int rec_employer_order_id
        {
            get { return frec_employer_order_id; }
            set { SetPropertyValue<int>("rec_employer_order_id", ref frec_employer_order_id, value); }
        }
        rec_Employer frec_employer_order_employer_id;
        [Association(@"rec_Employer_OrderReferencesrec_Employer")]
        public rec_Employer rec_employer_order_employer_id
        {
            get { return frec_employer_order_employer_id; }
            set { SetPropertyValue<rec_Employer>("rec_employer_order_employer_id", ref frec_employer_order_employer_id, value); }
        }
        DateTime frec_employer_order_date;
        public DateTime rec_employer_order_date
        {
            get { return frec_employer_order_date; }
            set { SetPropertyValue<DateTime>("rec_employer_order_date", ref frec_employer_order_date, value); }
        }
        string frec_employer_order_description;
        [Size(1000)]
        public string rec_employer_order_description
        {
            get { return frec_employer_order_description; }
            set { SetPropertyValue<string>("rec_employer_order_description", ref frec_employer_order_description, value); }
        }
        [Association(@"rec_Employer_Order_DetailReferencesrec_Employer_Order")]
        public XPCollection<rec_Employer_Order_Detail> rec_Employer_Order_Details { get { return GetCollection<rec_Employer_Order_Detail>("rec_Employer_Order_Details"); } }
    }

}
