//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Tag : XPLiteObject
    {
        int ftag_id;
        [Key(true)]
        public int tag_id
        {
            get { return ftag_id; }
            set { SetPropertyValue<int>("tag_id", ref ftag_id, value); }
        }
        string ftag_name;
        public string tag_name
        {
            get { return ftag_name; }
            set { SetPropertyValue<string>("tag_name", ref ftag_name, value); }
        }
    }

}
