//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Employer_Order : XPLiteObject
    {
        int frec_employer_order_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"Id")]
        public int rec_employer_order_id
        {
            get { return frec_employer_order_id; }
            set { SetPropertyValue<int>("rec_employer_order_id", ref frec_employer_order_id, value); }
        }
        rec_Employer frec_employer_order_employer_id;
        [Indexed(Name = @"irec_employer_order_employer_id_rec_Employer_Order")]
        [Association(@"rec_Employer_OrderReferencesrec_Employer")]
        [DevExpress.Xpo.DisplayName(@"Employer")]
        public rec_Employer rec_employer_order_employer_id
        {
            get { return frec_employer_order_employer_id; }
            set { SetPropertyValue<rec_Employer>("rec_employer_order_employer_id", ref frec_employer_order_employer_id, value); }
        }
        DateTime frec_employer_order_date;
        [DevExpress.Xpo.DisplayName(@"Order date")]
        public DateTime rec_employer_order_date
        {
            get { return frec_employer_order_date; }
            set { SetPropertyValue<DateTime>("rec_employer_order_date", ref frec_employer_order_date, value); }
        }
        string frec_employer_order_description;
        [Size(1000)]
        [DevExpress.Xpo.DisplayName(@"Description")]
        public string rec_employer_order_description
        {
            get { return frec_employer_order_description; }
            set { SetPropertyValue<string>("rec_employer_order_description", ref frec_employer_order_description, value); }
        }
        rec_Delivery_Type frec_employer_order_rec_delivery_type_id;
        [Indexed(Name = @"irec_employer_order_rec_delivery_type_id_rec_Employer_Order")]
        [Association(@"rec_Employer_OrderReferencesrec_Delivery_Type")]
        [DevExpress.Xpo.DisplayName(@"Delivery type")]
        public rec_Delivery_Type rec_employer_order_rec_delivery_type_id
        {
            get { return frec_employer_order_rec_delivery_type_id; }
            set { SetPropertyValue<rec_Delivery_Type>("rec_employer_order_rec_delivery_type_id", ref frec_employer_order_rec_delivery_type_id, value); }
        }
        DateTime frec_employer_order_delivery_date;
        [DevExpress.Xpo.DisplayName(@"Delivery date")]
        public DateTime rec_employer_order_delivery_date
        {
            get { return frec_employer_order_delivery_date; }
            set { SetPropertyValue<DateTime>("rec_employer_order_delivery_date", ref frec_employer_order_delivery_date, value); }
        }
        Core.Typez.enum_rec_Employer_Order_Status frec_employer_order_rec_employer_order_status_id;
        [Indexed(Name = @"irec_employer_order_rec_employer_order_status_id_rec_Employer_Order")]
        public Core.Typez.enum_rec_Employer_Order_Status rec_employer_order_rec_employer_order_status_id
        {
            get { return frec_employer_order_rec_employer_order_status_id; }
            set { SetPropertyValue<Core.Typez.enum_rec_Employer_Order_Status>("rec_employer_order_rec_employer_order_status_id", ref frec_employer_order_rec_employer_order_status_id, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Order Details")]
        [Association(@"rec_Employer_Order_DetailReferencesrec_Employer_Order")]
        public XPCollection<rec_Employer_Order_Detail> rec_Employer_Order_Details { get { return GetCollection<rec_Employer_Order_Detail>("rec_Employer_Order_Details"); } }
        [DevExpress.Xpo.DisplayName(@"Order Interviews")]
        [Association(@"rec_Employer_Order_InterviewReferencesrec_Employer_Order")]
        public XPCollection<rec_Employer_Order_Interview> rec_Employer_Order_Interviews { get { return GetCollection<rec_Employer_Order_Interview>("rec_Employer_Order_Interviews"); } }
        [DevExpress.Xpo.DisplayName(@"Employer Order Activities")]
        [Association(@"rec_Employer_Order_ActivityReferencesrec_Employer_Order")]
        public XPCollection<rec_Employer_Order_Activity> rec_Employer_Order_Activitys { get { return GetCollection<rec_Employer_Order_Activity>("rec_Employer_Order_Activitys"); } }
    }

}
