//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Employer_Order_Detail_Connection : XPLiteObject
    {
        int frec_employer_order_detail_connection_id;
        [Key(true)]
        public int rec_employer_order_detail_connection_id
        {
            get { return frec_employer_order_detail_connection_id; }
            set { SetPropertyValue<int>("rec_employer_order_detail_connection_id", ref frec_employer_order_detail_connection_id, value); }
        }
        rec_Employer_Order_Detail frec_employer_order_detail_id;
        [Association(@"rec_Employer_Order_Detail_ConnectionReferencesrec_Employer_Order_Detail")]
        public rec_Employer_Order_Detail rec_employer_order_detail_id
        {
            get { return frec_employer_order_detail_id; }
            set { SetPropertyValue<rec_Employer_Order_Detail>("rec_employer_order_detail_id", ref frec_employer_order_detail_id, value); }
        }
        DateTime frec_employer_order_detail_connection_date;
        public DateTime rec_employer_order_detail_connection_date
        {
            get { return frec_employer_order_detail_connection_date; }
            set { SetPropertyValue<DateTime>("rec_employer_order_detail_connection_date", ref frec_employer_order_detail_connection_date, value); }
        }
        [Association(@"rec_Employer_Order_Detail_Connection_DetailReferencesrec_Employer_Order_Detail_Connection")]
        public XPCollection<rec_Employer_Order_Detail_Connection_Detail> rec_Employer_Order_Detail_Connection_Details { get { return GetCollection<rec_Employer_Order_Detail_Connection_Detail>("rec_Employer_Order_Detail_Connection_Details"); } }
    }

}
