//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Marital_Status : XPLiteObject
    {
        int fmarital_status_id;
        [Key]
        public int marital_status_id
        {
            get { return fmarital_status_id; }
            set { SetPropertyValue<int>("marital_status_id", ref fmarital_status_id, value); }
        }
        string fmarital_status_name;
        public string marital_status_name
        {
            get { return fmarital_status_name; }
            set { SetPropertyValue<string>("marital_status_name", ref fmarital_status_name, value); }
        }
        [Association(@"rec_ApplicantReferencesrec_Marital_Status")]
        public XPCollection<rec_Applicant> rec_Applicants { get { return GetCollection<rec_Applicant>("rec_Applicants"); } }
    }

}
