//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_job_post : XPLiteObject
    {
        int fjob_post_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int job_post_id
        {
            get { return fjob_post_id; }
            set { SetPropertyValue<int>("job_post_id", ref fjob_post_id, value); }
        }
        string fjp_title;
        [Size(150)]
        [DevExpress.Xpo.DisplayName(@"Title")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_job_post_jp_title_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Title")]
        public string jp_title
        {
            get { return fjp_title; }
            set { SetPropertyValue<string>("jp_title", ref fjp_title, value); }
        }
        string fjp_content;
        [Size(1000)]
        [DevExpress.Xpo.DisplayName(@"Content")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_job_post_jp_content_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Content")]
        public string jp_content
        {
            get { return fjp_content; }
            set { SetPropertyValue<string>("jp_content", ref fjp_content, value); }
        }
        DateTime fjp_date_start;
        [DevExpress.Xpo.DisplayName(@"Aired in")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_job_post_jp_date_start_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Select Start From")]
        public DateTime jp_date_start
        {
            get { return fjp_date_start; }
            set { SetPropertyValue<DateTime>("jp_date_start", ref fjp_date_start, value); }
        }
        DateTime fjp_date_end;
        [DevExpress.Xpo.DisplayName(@"Aired to")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_job_post_jp_date_end_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Select End From")]
        public DateTime jp_date_end
        {
            get { return fjp_date_end; }
            set { SetPropertyValue<DateTime>("jp_date_end", ref fjp_date_end, value); }
        }
        rec_Industry fjp_industry_id;
        [Indexed(Name = @"ijp_industry_id_rec_job_post")]
        [Association(@"rec_job_postReferencesrec_Industry")]
        [DevExpress.Xpo.DisplayName(@"Industry")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_job_post_jp_industry_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Select Industry")]
        public rec_Industry jp_industry_id
        {
            get { return fjp_industry_id; }
            set { SetPropertyValue<rec_Industry>("jp_industry_id", ref fjp_industry_id, value); }
        }
        System.Drawing.Image fjp_image;
        [Size(SizeAttribute.Unlimited)]
        [ValueConverter(typeof(DevExpress.Xpo.Metadata.ImageValueConverter))]
        [MemberDesignTimeVisibility(true)]
        [DevExpress.Xpo.DisplayName(@"Photo")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_job_post_jp_image_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Select Photo")]
        public System.Drawing.Image jp_image
        {
            get { return fjp_image; }
            set { SetPropertyValue<System.Drawing.Image>("jp_image", ref fjp_image, value); }
        }
        bool fjp_visible;
        [DevExpress.Xpo.DisplayName(@"Visible Online")]
        public bool jp_visible
        {
            get { return fjp_visible; }
            set { SetPropertyValue<bool>("jp_visible", ref fjp_visible, value); }
        }
        int fjp_view_count;
        [DevExpress.Xpo.DisplayName(@"Number of views")]
        public int jp_view_count
        {
            get { return fjp_view_count; }
            set { SetPropertyValue<int>("jp_view_count", ref fjp_view_count, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Online Apply")]
        [Association(@"rec_job_post_applyReferencesrec_job_post")]
        public XPCollection<rec_job_post_apply> rec_job_post_applys { get { return GetCollection<rec_job_post_apply>("rec_job_post_applys"); } }
    }

}
