//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Employer_Order_Detail_Accept_Applicat_Doc : XPLiteObject
    {
        int frec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"Id")]
        public int rec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_id
        {
            get { return frec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_id; }
            set { SetPropertyValue<int>("rec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_id", ref frec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_id, value); }
        }
        rec_Employer_Order_Detail_Accept_Applicat frec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_employer_order_detail_accept_applicat_id;
        [Indexed(Name = @"irec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_employer_order_detail_accept_applicat_id_r_951B4CEE")]
        [Association(@"rec_Employer_Order_Detail_Accept_Applicat_DocReferencesrec_Employer_Order_Detail_Accept_Applicat")]
        [DevExpress.Xpo.DisplayName(@"Accepted_Applicant")]
        public rec_Employer_Order_Detail_Accept_Applicat rec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_employer_order_detail_accept_applicat_id
        {
            get { return frec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_employer_order_detail_accept_applicat_id; }
            set { SetPropertyValue<rec_Employer_Order_Detail_Accept_Applicat>("rec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_employer_order_detail_accept_applicat_id", ref frec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_employer_order_detail_accept_applicat_id, value); }
        }
        rec_Industry_Require_Doc_Info frec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_industry_require_doc_info_id;
        [Indexed(Name = @"irec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_industry_require_doc_info_id_rec_Employer__9B84962E")]
        [Association(@"rec_Employer_Order_Detail_Accept_Applicat_DocReferencesrec_Industry_Require_Doc_Info")]
        [DevExpress.Xpo.DisplayName(@"Required Doc")]
        public rec_Industry_Require_Doc_Info rec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_industry_require_doc_info_id
        {
            get { return frec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_industry_require_doc_info_id; }
            set { SetPropertyValue<rec_Industry_Require_Doc_Info>("rec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_industry_require_doc_info_id", ref frec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_industry_require_doc_info_id, value); }
        }
        rec_Require_Doc_Status frec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_require_doc_status_id;
        [Indexed(Name = @"irec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_require_doc_status_id_rec_Employer_Order_D_AA983B19")]
        [Association(@"rec_Employer_Order_Detail_Accept_Applicat_DocReferencesrec_Require_Doc_Status")]
        [DevExpress.Xpo.DisplayName(@"Status")]
        public rec_Require_Doc_Status rec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_require_doc_status_id
        {
            get { return frec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_require_doc_status_id; }
            set { SetPropertyValue<rec_Require_Doc_Status>("rec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_require_doc_status_id", ref frec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_rec_require_doc_status_id, value); }
        }
        string frec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_description;
        [Size(1000)]
        [DevExpress.Xpo.DisplayName(@"Description")]
        public string rec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_description
        {
            get { return frec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_description; }
            set { SetPropertyValue<string>("rec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_description", ref frec_employer_order_detail_accept_applicat_rec_industry_require_doc_type_description, value); }
        }
    }

}
