//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Employer_Order_Activity : XPLiteObject
    {
        int femp_order_activity_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int emp_order_activity_id
        {
            get { return femp_order_activity_id; }
            set { SetPropertyValue<int>("emp_order_activity_id", ref femp_order_activity_id, value); }
        }
        rec_Employer_Order frec_employer_order_id;
        [Indexed(Name = @"irec_employer_order_id_rec_Employer_Order_Activity")]
        [Association(@"rec_Employer_Order_ActivityReferencesrec_Employer_Order")]
        [DevExpress.Xpo.DisplayName(@"Order")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_Employer_Order_Activity_rec_employer_order_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Select Employee")]
        public rec_Employer_Order rec_employer_order_id
        {
            get { return frec_employer_order_id; }
            set { SetPropertyValue<rec_Employer_Order>("rec_employer_order_id", ref frec_employer_order_id, value); }
        }
        DateTime factivity_date;
        [DevExpress.Xpo.DisplayName(@"Activity date")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_Employer_Order_Activity_activity_date_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Date")]
        public DateTime activity_date
        {
            get { return factivity_date; }
            set { SetPropertyValue<DateTime>("activity_date", ref factivity_date, value); }
        }
        rec_Activity factivity_id;
        [Indexed(Name = @"iactivity_id_rec_Employer_Order_Activity")]
        [Association(@"rec_Employer_Order_ActivityReferencesrec_Activity")]
        [DevExpress.Xpo.DisplayName(@"Activity")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_Employer_Order_Activity_activity_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Select Activity")]
        public rec_Activity activity_id
        {
            get { return factivity_id; }
            set { SetPropertyValue<rec_Activity>("activity_id", ref factivity_id, value); }
        }
        rec_Cash fcash_id;
        [Indexed(Name = @"icash_id_rec_Employer_Order_Activity")]
        [Association(@"rec_Employer_Order_ActivityReferencesrec_Cash")]
        [DevExpress.Xpo.DisplayName(@"Cash")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_Employer_Order_Activity_cash_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Select Cash")]
        public rec_Cash cash_id
        {
            get { return fcash_id; }
            set { SetPropertyValue<rec_Cash>("cash_id", ref fcash_id, value); }
        }
        double fvalue1;
        [Persistent(@"value")]
        [DevExpress.Xpo.DisplayName(@"Value")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_Employer_Order_Activity_value_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Enter value")]
        public double value1
        {
            get { return fvalue1; }
            set { SetPropertyValue<double>("value1", ref fvalue1, value); }
        }
        double forg_value;
        [DevExpress.Xpo.DisplayName(@"Original Value")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_Employer_Order_Activity_org_value_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Original Value")]
        public double org_value
        {
            get { return forg_value; }
            set { SetPropertyValue<double>("org_value", ref forg_value, value); }
        }
        Accounting.BusinessObjects.Recruitment.acc_Currency fcurrency_id;
        [Indexed(Name = @"icurrency_id_rec_Employer_Order_Activity")]
        [DevExpress.Xpo.DisplayName(@"Currency")]
        public Accounting.BusinessObjects.Recruitment.acc_Currency currency_id
        {
            get { return fcurrency_id; }
            set { SetPropertyValue<Accounting.BusinessObjects.Recruitment.acc_Currency>("currency_id", ref fcurrency_id, value); }
        }
        Accounting.BusinessObjects.Recruitment.acc_Journal_Entry fjour_entry_id;
        [Indexed(Name = @"ijour_entry_id_rec_Employer_Order_Activity")]
        [DevExpress.Xpo.DisplayName(@"Journal Entry")]
        public Accounting.BusinessObjects.Recruitment.acc_Journal_Entry jour_entry_id
        {
            get { return fjour_entry_id; }
            set { SetPropertyValue<Accounting.BusinessObjects.Recruitment.acc_Journal_Entry>("jour_entry_id", ref fjour_entry_id, value); }
        }
        string fvoucher_no;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Voucher Number")]
        public string voucher_no
        {
            get { return fvoucher_no; }
            set { SetPropertyValue<string>("voucher_no", ref fvoucher_no, value); }
        }
    }

}
