//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Employer_Order_Detail_Suggest_Applicat : XPLiteObject
    {
        int frec_employer_order_detail_suggest_applicat_id;
        [Key(true)]
        public int rec_employer_order_detail_suggest_applicat_id
        {
            get { return frec_employer_order_detail_suggest_applicat_id; }
            set { SetPropertyValue<int>("rec_employer_order_detail_suggest_applicat_id", ref frec_employer_order_detail_suggest_applicat_id, value); }
        }
        rec_Employer_Order_Detail frec_employer_order_detail_suggest_applicat_rec_employer_order_detail_id;
        [Indexed(Name = @"irec_employer_order_detail_suggest_applicat_rec_employer_order_detail_id_rec_Employer_Order_Detail_Suggest_Applicat")]
        [Association(@"rec_Employer_Order_Detail_Suggest_ApplicatReferencesrec_Employer_Order_Detail")]
        public rec_Employer_Order_Detail rec_employer_order_detail_suggest_applicat_rec_employer_order_detail_id
        {
            get { return frec_employer_order_detail_suggest_applicat_rec_employer_order_detail_id; }
            set { SetPropertyValue<rec_Employer_Order_Detail>("rec_employer_order_detail_suggest_applicat_rec_employer_order_detail_id", ref frec_employer_order_detail_suggest_applicat_rec_employer_order_detail_id, value); }
        }
        rec_Applicant frec_employer_order_detail_suggest_applicat_applicant_id;
        [Indexed(Name = @"irec_employer_order_detail_suggest_applicat_applicant_id_rec_Employer_Order_Detail_Suggest_Applicat")]
        [Association(@"rec_Employer_Order_Detail_Suggest_ApplicatReferencesrec_Applicant")]
        public rec_Applicant rec_employer_order_detail_suggest_applicat_applicant_id
        {
            get { return frec_employer_order_detail_suggest_applicat_applicant_id; }
            set { SetPropertyValue<rec_Applicant>("rec_employer_order_detail_suggest_applicat_applicant_id", ref frec_employer_order_detail_suggest_applicat_applicant_id, value); }
        }
        rec_Suggest_Applicat_Source frec_employer_order_detail_suggest_applicat_rec_suggest_applicat_source_id;
        [Indexed(Name = @"irec_employer_order_detail_suggest_applicat_rec_suggest_applicat_source_id_rec_Employer_Order_Detail_Suggest_Applicat")]
        [Association(@"rec_Employer_Order_Detail_Suggest_ApplicatReferencesrec_Suggest_Applicat_Source")]
        public rec_Suggest_Applicat_Source rec_employer_order_detail_suggest_applicat_rec_suggest_applicat_source_id
        {
            get { return frec_employer_order_detail_suggest_applicat_rec_suggest_applicat_source_id; }
            set { SetPropertyValue<rec_Suggest_Applicat_Source>("rec_employer_order_detail_suggest_applicat_rec_suggest_applicat_source_id", ref frec_employer_order_detail_suggest_applicat_rec_suggest_applicat_source_id, value); }
        }
        string frec_employer_order_detail_suggest_applicat_description;
        [Size(1000)]
        public string rec_employer_order_detail_suggest_applicat_description
        {
            get { return frec_employer_order_detail_suggest_applicat_description; }
            set { SetPropertyValue<string>("rec_employer_order_detail_suggest_applicat_description", ref frec_employer_order_detail_suggest_applicat_description, value); }
        }
        [Association(@"rec_Employer_Order_Detail_Accept_ApplicatReferencesrec_Employer_Order_Detail_Suggest_Applicat"), Aggregated]
        public XPCollection<rec_Employer_Order_Detail_Accept_Applicat> rec_Employer_Order_Detail_Accept_Applicats { get { return GetCollection<rec_Employer_Order_Detail_Accept_Applicat>("rec_Employer_Order_Detail_Accept_Applicats"); } }

    }

}
