//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Employer : XPLiteObject
    {
        int femployer_id;
        [Key(true)]
        public int employer_id
        {
            get { return femployer_id; }
            set { SetPropertyValue<int>("employer_id", ref femployer_id, value); }
        }
        string femployer_name;
        public string employer_name
        {
            get { return femployer_name; }
            set { SetPropertyValue<string>("employer_name", ref femployer_name, value); }
        }
        string femployer_Address;
        public string employer_Address
        {
            get { return femployer_Address; }
            set { SetPropertyValue<string>("employer_Address", ref femployer_Address, value); }
        }
    }

}
