//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Doc_Info : XPLiteObject
    {
        int frec_doc_info_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"Id")]
        public int rec_doc_info_id
        {
            get { return frec_doc_info_id; }
            set { SetPropertyValue<int>("rec_doc_info_id", ref frec_doc_info_id, value); }
        }
        string frec_doc_info_name;
        [DevExpress.Xpo.DisplayName(@"Doc name")]
        [DevExpress.Persistent.Validation.RuleUniqueValue("", DevExpress.Persistent.Validation.DefaultContexts.Save, "Object with the same name exists")]
        public string rec_doc_info_name
        {
            get { return frec_doc_info_name; }
            set { SetPropertyValue<string>("rec_doc_info_name", ref frec_doc_info_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Industry Required Doc")]
        [Association(@"rec_Industry_Require_Doc_InfoReferencesrec_Doc_Info")]
        public XPCollection<rec_Industry_Require_Doc_Info> rec_Industry_Require_Doc_Infos { get { return GetCollection<rec_Industry_Require_Doc_Info>("rec_Industry_Require_Doc_Infos"); } }
        [DevExpress.Xpo.DisplayName(@"Document Service Order Details")]
        [Association(@"rec_DocSrv_Order_DetailReferencesrec_Doc_Info")]
        public XPCollection<rec_DocSrv_Order_Detail> rec_DocSrv_Order_Details { get { return GetCollection<rec_DocSrv_Order_Detail>("rec_DocSrv_Order_Details"); } }
    }

}
