//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Industry_Require_Doc_Info : XPLiteObject
    {
        int frec_industry_require_doc_info_id;
        [Key(true)]
        public int rec_industry_require_doc_info_id
        {
            get { return frec_industry_require_doc_info_id; }
            set { SetPropertyValue<int>("rec_industry_require_doc_info_id", ref frec_industry_require_doc_info_id, value); }
        }
        rec_Doc_Info frec_industry_require_doc_info_rec_doc_info_id;
        [Association(@"rec_Industry_Require_Doc_InfoReferencesrec_Doc_Info")]
        public rec_Doc_Info rec_industry_require_doc_info_rec_doc_info_id
        {
            get { return frec_industry_require_doc_info_rec_doc_info_id; }
            set { SetPropertyValue<rec_Doc_Info>("rec_industry_require_doc_info_rec_doc_info_id", ref frec_industry_require_doc_info_rec_doc_info_id, value); }
        }
        rec_Industry frec_industry_require_doc_info_industry_id;
        [Association(@"rec_Industry_Require_Doc_InfoReferencesrec_Industry")]
        public rec_Industry rec_industry_require_doc_info_industry_id
        {
            get { return frec_industry_require_doc_info_industry_id; }
            set { SetPropertyValue<rec_Industry>("rec_industry_require_doc_info_industry_id", ref frec_industry_require_doc_info_industry_id, value); }
        }
        [Association(@"rec_Employer_Order_Detail_Accept_Applicat_DocReferencesrec_Industry_Require_Doc_Info")]
        public XPCollection<rec_Employer_Order_Detail_Accept_Applicat_Doc> rec_Employer_Order_Detail_Accept_Applicat_Docs { get { return GetCollection<rec_Employer_Order_Detail_Accept_Applicat_Doc>("rec_Employer_Order_Detail_Accept_Applicat_Docs"); } }
    }

}
