//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Applicant_Experience : XPLiteObject
    {
        int fapp_exp_id;
        [Key(true)]
        public int app_exp_id
        {
            get { return fapp_exp_id; }
            set { SetPropertyValue<int>("app_exp_id", ref fapp_exp_id, value); }
        }
        rec_Applicant fapp_exp_applicant_id;
        [Indexed(Name = @"iapp_exp_applicant_id_rec_Applicant_Experience")]
        [Association(@"rec_Applicant_ExperienceReferencesrec_Applicant")]
        public rec_Applicant app_exp_applicant_id
        {
            get { return fapp_exp_applicant_id; }
            set { SetPropertyValue<rec_Applicant>("app_exp_applicant_id", ref fapp_exp_applicant_id, value); }
        }
        string fapp_exp_title;
        public string app_exp_title
        {
            get { return fapp_exp_title; }
            set { SetPropertyValue<string>("app_exp_title", ref fapp_exp_title, value); }
        }
        string femployer_name;
        public string employer_name
        {
            get { return femployer_name; }
            set { SetPropertyValue<string>("employer_name", ref femployer_name, value); }
        }
        DateTime fapp_exp_start_date;
        public DateTime app_exp_start_date
        {
            get { return fapp_exp_start_date; }
            set { SetPropertyValue<DateTime>("app_exp_start_date", ref fapp_exp_start_date, value); }
        }
        DateTime fapp_exp_end_date;
        public DateTime app_exp_end_date
        {
            get { return fapp_exp_end_date; }
            set { SetPropertyValue<DateTime>("app_exp_end_date", ref fapp_exp_end_date, value); }
        }
        rec_Industry fapp_exp_industry_id;
        [Indexed(Name = @"iapp_exp_industry_id_rec_Applicant_Experience")]
        [Association(@"rec_Applicant_ExperienceReferencesrec_Industry")]
        public rec_Industry app_exp_industry_id
        {
            get { return fapp_exp_industry_id; }
            set { SetPropertyValue<rec_Industry>("app_exp_industry_id", ref fapp_exp_industry_id, value); }
        }
        rec_Work_Type fapp_exp_work_type_id;
        [Indexed(Name = @"iapp_exp_work_type_id_rec_Applicant_Experience")]
        [Association(@"rec_Applicant_ExperienceReferencesrec_Work_Type")]
        public rec_Work_Type app_exp_work_type_id
        {
            get { return fapp_exp_work_type_id; }
            set { SetPropertyValue<rec_Work_Type>("app_exp_work_type_id", ref fapp_exp_work_type_id, value); }
        }
        string fapp_exp_description;
        [Size(1000)]
        public string app_exp_description
        {
            get { return fapp_exp_description; }
            set { SetPropertyValue<string>("app_exp_description", ref fapp_exp_description, value); }
        }
        rec_Job fapp_exp_job_id;
        [Indexed(Name = @"iapp_exp_job_id_rec_Applicant_Experience")]
        [Association(@"rec_Applicant_ExperienceReferencesrec_Job")]
        public rec_Job app_exp_job_id
        {
            get { return fapp_exp_job_id; }
            set { SetPropertyValue<rec_Job>("app_exp_job_id", ref fapp_exp_job_id, value); }
        }
        bool fapp_exp_end_date_till_now;
        public bool app_exp_end_date_till_now
        {
            get { return fapp_exp_end_date_till_now; }
            set { SetPropertyValue<bool>("app_exp_end_date_till_now", ref fapp_exp_end_date_till_now, value); }
        }
    }

}
