//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Cash : XPLiteObject
    {
        int fcash_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int cash_id
        {
            get { return fcash_id; }
            set { SetPropertyValue<int>("cash_id", ref fcash_id, value); }
        }
        string fcash_name;
        [DevExpress.Xpo.DisplayName(@"Name")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_Cash_cash_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Name")]
        public string cash_name
        {
            get { return fcash_name; }
            set { SetPropertyValue<string>("cash_name", ref fcash_name, value); }
        }
        Accounting.BusinessObjects.Recruitment.acc_Account faccount_id;
        [Indexed(Name = @"iaccount_id_rec_Cash")]
        [DevExpress.Xpo.DisplayName(@"Account")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_Cash_account_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Select Account")]
        public Accounting.BusinessObjects.Recruitment.acc_Account account_id
        {
            get { return faccount_id; }
            set { SetPropertyValue<Accounting.BusinessObjects.Recruitment.acc_Account>("account_id", ref faccount_id, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Accepted Applicant Activities")]
        [Association(@"rec_Accept_App_ActivityReferencesrec_Cash")]
        public XPCollection<rec_Accept_App_Activity> rec_Accept_App_Activitys { get { return GetCollection<rec_Accept_App_Activity>("rec_Accept_App_Activitys"); } }
        [DevExpress.Xpo.DisplayName(@"Employer Order Activities")]
        [Association(@"rec_Employer_Order_ActivityReferencesrec_Cash")]
        public XPCollection<rec_Employer_Order_Activity> rec_Employer_Order_Activitys { get { return GetCollection<rec_Employer_Order_Activity>("rec_Employer_Order_Activitys"); } }
    }

}
