//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Require_Doc_Status : XPLiteObject
    {
        int frec_require_doc_status_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"Id")]
        public int rec_require_doc_status_id
        {
            get { return frec_require_doc_status_id; }
            set { SetPropertyValue<int>("rec_require_doc_status_id", ref frec_require_doc_status_id, value); }
        }
        string frec_require_doc_status_name;
        [DevExpress.Xpo.DisplayName(@"Status name")]
        public string rec_require_doc_status_name
        {
            get { return frec_require_doc_status_name; }
            set { SetPropertyValue<string>("rec_require_doc_status_name", ref frec_require_doc_status_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Accepted Applicant Documents")]
        [Association(@"rec_Employer_Order_Detail_Accept_Applicat_DocReferencesrec_Require_Doc_Status")]
        public XPCollection<rec_Employer_Order_Detail_Accept_Applicat_Doc> rec_Employer_Order_Detail_Accept_Applicat_Docs { get { return GetCollection<rec_Employer_Order_Detail_Accept_Applicat_Doc>("rec_Employer_Order_Detail_Accept_Applicat_Docs"); } }
    }

}
