//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Medical_Insurance_Types : XPLiteObject
    {
        int frec_medical_insurance_types_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"Id")]
        public int rec_medical_insurance_types_id
        {
            get { return frec_medical_insurance_types_id; }
            set { SetPropertyValue<int>("rec_medical_insurance_types_id", ref frec_medical_insurance_types_id, value); }
        }
        string frec_medical_insurance_types_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Medical insurance")]
        public string rec_medical_insurance_types_name
        {
            get { return frec_medical_insurance_types_name; }
            set { SetPropertyValue<string>("rec_medical_insurance_types_name", ref frec_medical_insurance_types_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Order Details")]
        [Association(@"rec_Employer_Order_DetailReferencesrec_Medical_Insurance_Types")]
        public XPCollection<rec_Employer_Order_Detail> rec_Employer_Order_Details { get { return GetCollection<rec_Employer_Order_Detail>("rec_Employer_Order_Details"); } }
    }

}
