//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Employer_Order_Status : XPLiteObject
    {
        int frec_employer_order_status_id;
        [Key(true)]
        public int rec_employer_order_status_id
        {
            get { return frec_employer_order_status_id; }
            set { SetPropertyValue<int>("rec_employer_order_status_id", ref frec_employer_order_status_id, value); }
        }
        string frec_employer_order_status_name;
        [Size(50)]
        public string rec_employer_order_status_name
        {
            get { return frec_employer_order_status_name; }
            set { SetPropertyValue<string>("rec_employer_order_status_name", ref frec_employer_order_status_name, value); }
        }
    }

}
