//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Employer_Industry : XPLiteObject
    {
        int femployer_industry_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"Id")]
        public int employer_industry_id
        {
            get { return femployer_industry_id; }
            set { SetPropertyValue<int>("employer_industry_id", ref femployer_industry_id, value); }
        }
        rec_Employer femployer_id;
        [Indexed(Name = @"iemployer_id_rec_Employer_Industry")]
        [Association(@"rec_Employer_IndustryReferencesrec_Employer")]
        [DevExpress.Xpo.DisplayName(@"Employer")]
        public rec_Employer employer_id
        {
            get { return femployer_id; }
            set { SetPropertyValue<rec_Employer>("employer_id", ref femployer_id, value); }
        }
        rec_Industry findustry_id;
        [Indexed(Name = @"iindustry_id_rec_Employer_Industry")]
        [Association(@"rec_Employer_IndustryReferencesrec_Industry")]
        [DevExpress.Xpo.DisplayName(@"Industry")]
        public rec_Industry industry_id
        {
            get { return findustry_id; }
            set { SetPropertyValue<rec_Industry>("industry_id", ref findustry_id, value); }
        }
    }

}
