//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Delivery_Type : XPLiteObject
    {
        int frec_delivery_type_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"Id")]
        public int rec_delivery_type_id
        {
            get { return frec_delivery_type_id; }
            set { SetPropertyValue<int>("rec_delivery_type_id", ref frec_delivery_type_id, value); }
        }
        string frec_delivery_type_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Delivery type")]
        public string rec_delivery_type_name
        {
            get { return frec_delivery_type_name; }
            set { SetPropertyValue<string>("rec_delivery_type_name", ref frec_delivery_type_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Orders")]
        [Association(@"rec_Employer_OrderReferencesrec_Delivery_Type")]
        public XPCollection<rec_Employer_Order> rec_Employer_Orders { get { return GetCollection<rec_Employer_Order>("rec_Employer_Orders"); } }
    }

}
