//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Employer_Order_Detail_Connection_Detail : XPLiteObject
    {
        int frec_employer_order_detail_connection_detail_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"Id")]
        public int rec_employer_order_detail_connection_detail_id
        {
            get { return frec_employer_order_detail_connection_detail_id; }
            set { SetPropertyValue<int>("rec_employer_order_detail_connection_detail_id", ref frec_employer_order_detail_connection_detail_id, value); }
        }
        rec_Employer_Order_Detail_Connection frec_employer_order_detail_connection_id;
        [Indexed(Name = @"irec_employer_order_detail_connection_id_rec_Employer_Order_Detail_Connection_Detail")]
        [Association(@"rec_Employer_Order_Detail_Connection_DetailReferencesrec_Employer_Order_Detail_Connection")]
        [DevExpress.Xpo.DisplayName(@"Connection")]
        public rec_Employer_Order_Detail_Connection rec_employer_order_detail_connection_id
        {
            get { return frec_employer_order_detail_connection_id; }
            set { SetPropertyValue<rec_Employer_Order_Detail_Connection>("rec_employer_order_detail_connection_id", ref frec_employer_order_detail_connection_id, value); }
        }
        rec_Applicant frec_employer_order_detail_connection_detail_applicant_id;
        [Indexed(Name = @"irec_employer_order_detail_connection_detail_applicant_id_rec_Employer_Order_Detail_Connection_Detail")]
        [Association(@"rec_Employer_Order_Detail_Connection_DetailReferencesrec_Applicant")]
        [DevExpress.Xpo.DisplayName(@"Applicant")]
        public rec_Applicant rec_employer_order_detail_connection_detail_applicant_id
        {
            get { return frec_employer_order_detail_connection_detail_applicant_id; }
            set { SetPropertyValue<rec_Applicant>("rec_employer_order_detail_connection_detail_applicant_id", ref frec_employer_order_detail_connection_detail_applicant_id, value); }
        }
    }

}
