//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Accept_App_Activity : XPLiteObject
    {
        int faccept_app_activity_id;
        [Indexed(Name = @"PK_rec_accept_app_activity_id", Unique = true)]
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int accept_app_activity_id
        {
            get { return faccept_app_activity_id; }
            set { SetPropertyValue<int>("accept_app_activity_id", ref faccept_app_activity_id, value); }
        }
        rec_Employer_Order_Detail_Accept_Applicat frec_employer_order_detail_accept_applicat_rec_employer_order_detail_suggest_applicat_id;
        [Indexed(Name = @"irec_employer_order_detail_accept_applicat_rec_employer_order_detail_suggest_applicat_id_rec_Accept_App_Activity")]
        [Association(@"rec_Accept_App_ActivityReferencesrec_Employer_Order_Detail_Accept_Applicat")]
        [DevExpress.Xpo.DisplayName(@"Accepted Applicant")]
        public rec_Employer_Order_Detail_Accept_Applicat rec_employer_order_detail_accept_applicat_rec_employer_order_detail_suggest_applicat_id
        {
            get { return frec_employer_order_detail_accept_applicat_rec_employer_order_detail_suggest_applicat_id; }
            set { SetPropertyValue<rec_Employer_Order_Detail_Accept_Applicat>("rec_employer_order_detail_accept_applicat_rec_employer_order_detail_suggest_applicat_id", ref frec_employer_order_detail_accept_applicat_rec_employer_order_detail_suggest_applicat_id, value); }
        }
        DateTime factivity_date;
        [DevExpress.Xpo.DisplayName(@"Activity Date")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_Accept_App_Activity_activity_date_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter A Date")]
        public DateTime activity_date
        {
            get { return factivity_date; }
            set { SetPropertyValue<DateTime>("activity_date", ref factivity_date, value); }
        }
        rec_Activity factivity_id;
        [Indexed(Name = @"iactivity_id_rec_Accept_App_Activity")]
        [Association(@"rec_Accept_App_ActivityReferencesrec_Activity")]
        [DevExpress.Xpo.DisplayName(@"Activity")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_Accept_App_Activity_activity_activity_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Select Activity")
]
        public rec_Activity activity_id
        {
            get { return factivity_id; }
            set { SetPropertyValue<rec_Activity>("activity_id", ref factivity_id, value); }
        }
        rec_Cash fcash_id;
        [Indexed(Name = @"icash_id_rec_Accept_App_Activity")]
        [Association(@"rec_Accept_App_ActivityReferencesrec_Cash")]
        [DevExpress.Xpo.DisplayName(@"Cash")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_Accept_App_Activity_activity_cash_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Select Cash")]
        public rec_Cash cash_id
        {
            get { return fcash_id; }
            set { SetPropertyValue<rec_Cash>("cash_id", ref fcash_id, value); }
        }
        double fvalue1;
        [Persistent(@"value")]
        [DevExpress.Xpo.DisplayName(@"Value")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_Accept_App_Activity_activity_value_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter A Value")]
        public double value1
        {
            get { return fvalue1; }
            set { SetPropertyValue<double>("value1", ref fvalue1, value); }
        }
        double forg_value;
        [DevExpress.Xpo.DisplayName(@"Original Value")]
        public double org_value
        {
            get { return forg_value; }
            set { SetPropertyValue<double>("org_value", ref forg_value, value); }
        }
        Accounting.BusinessObjects.Recruitment.acc_Currency fcurrency_id;
        [Indexed(Name = @"icurrency_id_rec_Accept_App_Activity")]
        [DevExpress.Xpo.DisplayName(@"Currency")]
        public Accounting.BusinessObjects.Recruitment.acc_Currency currency_id
        {
            get { return fcurrency_id; }
            set { SetPropertyValue<Accounting.BusinessObjects.Recruitment.acc_Currency>("currency_id", ref fcurrency_id, value); }
        }
        Accounting.BusinessObjects.Recruitment.acc_Journal_Entry fjour_entry_id;
        [Indexed(Name = @"ijour_entry_id_rec_Accept_App_Activity")]
        [DevExpress.Xpo.DisplayName(@"Journal Entry")]
        public Accounting.BusinessObjects.Recruitment.acc_Journal_Entry jour_entry_id
        {
            get { return fjour_entry_id; }
            set { SetPropertyValue<Accounting.BusinessObjects.Recruitment.acc_Journal_Entry>("jour_entry_id", ref fjour_entry_id, value); }
        }
        string fvoucher_no;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Voucher Number")]
        public string voucher_no
        {
            get { return fvoucher_no; }
            set { SetPropertyValue<string>("voucher_no", ref fvoucher_no, value); }
        }
        string fdescription;
        [Size(1000)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
    }

}
