//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Employer : XPLiteObject
    {
        int femployer_id;
        [Key(true)]
        public int employer_id
        {
            get { return femployer_id; }
            set { SetPropertyValue<int>("employer_id", ref femployer_id, value); }
        }
        string femployer_name;
        public string employer_name
        {
            get { return femployer_name; }
            set { SetPropertyValue<string>("employer_name", ref femployer_name, value); }
        }
        string femployer_Address;
        public string employer_Address
        {
            get { return femployer_Address; }
            set { SetPropertyValue<string>("employer_Address", ref femployer_Address, value); }
        }
        string femployer_email;
        [Size(50)]
        public string employer_email
        {
            get { return femployer_email; }
            set { SetPropertyValue<string>("employer_email", ref femployer_email, value); }
        }
        rec_City femployer_city_id;
        [Indexed(Name = @"iemployer_city_id_rec_Employer")]
        [Association(@"rec_EmployerReferencesrec_City")]
        public rec_City employer_city_id
        {
            get { return femployer_city_id; }
            set { SetPropertyValue<rec_City>("employer_city_id", ref femployer_city_id, value); }
        }
        rec_Gender femployer_gender_id;
        [Indexed(Name = @"iemployer_gender_id_rec_Employer")]
        [Association(@"rec_EmployerReferencesrec_Gender")]
        public rec_Gender employer_gender_id
        {
            get { return femployer_gender_id; }
            set { SetPropertyValue<rec_Gender>("employer_gender_id", ref femployer_gender_id, value); }
        }
        string femployer_national_id;
        [Size(50)]
        public string employer_national_id
        {
            get { return femployer_national_id; }
            set { SetPropertyValue<string>("employer_national_id", ref femployer_national_id, value); }
        }
        string femployer_phone;
        [Size(50)]
        public string employer_phone
        {
            get { return femployer_phone; }
            set { SetPropertyValue<string>("employer_phone", ref femployer_phone, value); }
        }
        string femployer_mobile;
        [Size(50)]
        public string employer_mobile
        {
            get { return femployer_mobile; }
            set { SetPropertyValue<string>("employer_mobile", ref femployer_mobile, value); }
        }
        rec_Nationality femployer_nationality_id;
        [Indexed(Name = @"iemployer_nationality_id_rec_Employer")]
        [Association(@"rec_EmployerReferencesrec_Nationality")]
        public rec_Nationality employer_nationality_id
        {
            get { return femployer_nationality_id; }
            set { SetPropertyValue<rec_Nationality>("employer_nationality_id", ref femployer_nationality_id, value); }
        }
        string femployer_company_name;
        public string employer_company_name
        {
            get { return femployer_company_name; }
            set { SetPropertyValue<string>("employer_company_name", ref femployer_company_name, value); }
        }
        [Association(@"rec_Employer_OrderReferencesrec_Employer")]
        public XPCollection<rec_Employer_Order> rec_Employer_Orders { get { return GetCollection<rec_Employer_Order>("rec_Employer_Orders"); } }
    }

}
