//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Applicant_Status : XPLiteObject
    {
        int frec_applicant_status_id;
        [Key(true)]
        public int rec_applicant_status_id
        {
            get { return frec_applicant_status_id; }
            set { SetPropertyValue<int>("rec_applicant_status_id", ref frec_applicant_status_id, value); }
        }
        string frec_applicant_status_name;
        public string rec_applicant_status_name
        {
            get { return frec_applicant_status_name; }
            set { SetPropertyValue<string>("rec_applicant_status_name", ref frec_applicant_status_name, value); }
        }
        [Association(@"rec_Employer_Order_Detail_Accept_ApplicatReferencesrec_Applicant_Status")]
        public XPCollection<rec_Employer_Order_Detail_Accept_Applicat> rec_Employer_Order_Detail_Accept_Applicats { get { return GetCollection<rec_Employer_Order_Detail_Accept_Applicat>("rec_Employer_Order_Detail_Accept_Applicats"); } }
    }

}
