//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Study_Grade : XPLiteObject
    {
        int fstudy_grade_id;
        [Key]
        public int study_grade_id
        {
            get { return fstudy_grade_id; }
            set { SetPropertyValue<int>("study_grade_id", ref fstudy_grade_id, value); }
        }
        string fstudy_grade_name;
        public string study_grade_name
        {
            get { return fstudy_grade_name; }
            set { SetPropertyValue<string>("study_grade_name", ref fstudy_grade_name, value); }
        }
        [Association(@"rec_Applicant_StudyReferencesrec_Study_Grade")]
        public XPCollection<rec_Applicant_Study> rec_Applicant_Studys { get { return GetCollection<rec_Applicant_Study>("rec_Applicant_Studys"); } }
    }

}
