//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Nationality : XPLiteObject
    {
        int fnationality_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"Id")]
        public int nationality_id
        {
            get { return fnationality_id; }
            set { SetPropertyValue<int>("nationality_id", ref fnationality_id, value); }
        }
        string fnationality_name;
        [DevExpress.Xpo.DisplayName(@"Nationality name")]
        [DevExpress.Persistent.Validation.RuleUniqueValue("", DevExpress.Persistent.Validation.DefaultContexts.Save, "Object with the same name exists")]
        public string nationality_name
        {
            get { return fnationality_name; }
            set { SetPropertyValue<string>("nationality_name", ref fnationality_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Applicants")]
        [Association(@"rec_ApplicantReferencesrec_Nationality")]
        public XPCollection<rec_Applicant> rec_Applicants { get { return GetCollection<rec_Applicant>("rec_Applicants"); } }
        [DevExpress.Xpo.DisplayName(@"Employers")]
        [Association(@"rec_EmployerReferencesrec_Nationality")]
        public XPCollection<rec_Employer> rec_Employers { get { return GetCollection<rec_Employer>("rec_Employers"); } }
    }

}
