//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Employer_Order_Detail_Call : XPLiteObject
    {
        int frec_employer_order_detail_call_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"Id")]
        public int rec_employer_order_detail_call_id
        {
            get { return frec_employer_order_detail_call_id; }
            set { SetPropertyValue<int>("rec_employer_order_detail_call_id", ref frec_employer_order_detail_call_id, value); }
        }
        rec_Employer_Order_Detail frec_employer_order_detail_call_rec_employer_order_detail_id;
        [Association(@"rec_Employer_Order_Detail_CallReferencesrec_Employer_Order_Detail")]
        [DevExpress.Xpo.DisplayName(@"Order Detail")]
        public rec_Employer_Order_Detail rec_employer_order_detail_call_rec_employer_order_detail_id
        {
            get { return frec_employer_order_detail_call_rec_employer_order_detail_id; }
            set { SetPropertyValue<rec_Employer_Order_Detail>("rec_employer_order_detail_call_rec_employer_order_detail_id", ref frec_employer_order_detail_call_rec_employer_order_detail_id, value); }
        }
        rec_Applicant frec_employer_order_detail_call_applicant_id;
        [Indexed(Name = @"irec_employer_order_detail_call_applicant_id_rec_Employer_Order_Detail_Call")]
        [Association(@"rec_Employer_Order_Detail_CallReferencesrec_Applicant")]
        [DevExpress.Xpo.DisplayName(@"Applicant")]
        public rec_Applicant rec_employer_order_detail_call_applicant_id
        {
            get { return frec_employer_order_detail_call_applicant_id; }
            set { SetPropertyValue<rec_Applicant>("rec_employer_order_detail_call_applicant_id", ref frec_employer_order_detail_call_applicant_id, value); }
        }
        DateTime frec_employer_order_detail_call_date;
        [DevExpress.Xpo.DisplayName(@"Call date")]
        public DateTime rec_employer_order_detail_call_date
        {
            get { return frec_employer_order_detail_call_date; }
            set { SetPropertyValue<DateTime>("rec_employer_order_detail_call_date", ref frec_employer_order_detail_call_date, value); }
        }
        rec_Call_Result frec_employer_order_detail_call_rec_call_result_id;
        [Indexed(Name = @"irec_employer_order_detail_call_rec_call_result_id_rec_Employer_Order_Detail_Call")]
        [Association(@"rec_Employer_Order_Detail_CallReferencesrec_Call_Result")]
        [DevExpress.Xpo.DisplayName(@"Call result")]
        public rec_Call_Result rec_employer_order_detail_call_rec_call_result_id
        {
            get { return frec_employer_order_detail_call_rec_call_result_id; }
            set { SetPropertyValue<rec_Call_Result>("rec_employer_order_detail_call_rec_call_result_id", ref frec_employer_order_detail_call_rec_call_result_id, value); }
        }
        string frec_employer_order_detail_call_description;
        [Size(1000)]
        [DevExpress.Xpo.DisplayName(@"Description")]
        public string rec_employer_order_detail_call_description
        {
            get { return frec_employer_order_detail_call_description; }
            set { SetPropertyValue<string>("rec_employer_order_detail_call_description", ref frec_employer_order_detail_call_description, value); }
        }
    }

}
