//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Suggest_Applicat_Source : XPLiteObject
    {
        int frec_suggest_applicat_source_id;
        [Key(true)]
        public int rec_suggest_applicat_source_id
        {
            get { return frec_suggest_applicat_source_id; }
            set { SetPropertyValue<int>("rec_suggest_applicat_source_id", ref frec_suggest_applicat_source_id, value); }
        }
        string frec_suggest_applicat_source_name;
        [Size(50)]
        public string rec_suggest_applicat_source_name
        {
            get { return frec_suggest_applicat_source_name; }
            set { SetPropertyValue<string>("rec_suggest_applicat_source_name", ref frec_suggest_applicat_source_name, value); }
        }
        [Association(@"rec_Employer_Order_Detail_Suggest_ApplicatReferencesrec_Suggest_Applicat_Source")]
        public XPCollection<rec_Employer_Order_Detail_Suggest_Applicat> rec_Employer_Order_Detail_Suggest_Applicats { get { return GetCollection<rec_Employer_Order_Detail_Suggest_Applicat>("rec_Employer_Order_Detail_Suggest_Applicats"); } }
    }

}
