//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Applicant : XPLiteObject
    {
        int fapplicant_id;
        [Key(true)]
        public int applicant_id
        {
            get { return fapplicant_id; }
            set { SetPropertyValue<int>("applicant_id", ref fapplicant_id, value); }
        }
        string fapplicant_name;
        public string applicant_name
        {
            get { return fapplicant_name; }
            set { SetPropertyValue<string>("applicant_name", ref fapplicant_name, value); }
        }
        string fapplicant_email;
        [Size(50)]
        public string applicant_email
        {
            get { return fapplicant_email; }
            set { SetPropertyValue<string>("applicant_email", ref fapplicant_email, value); }
        }
        rec_City fapplicant_city_id;
        [Indexed(Name = @"iapplicant_city_id_rec_Applicant")]
        [Association(@"rec_ApplicantReferencesrec_City")]
        public rec_City applicant_city_id
        {
            get { return fapplicant_city_id; }
            set { SetPropertyValue<rec_City>("applicant_city_id", ref fapplicant_city_id, value); }
        }
        string fapplicant_phone;
        [Size(50)]
        public string applicant_phone
        {
            get { return fapplicant_phone; }
            set { SetPropertyValue<string>("applicant_phone", ref fapplicant_phone, value); }
        }
        string fapplicant_mobile;
        [Size(50)]
        public string applicant_mobile
        {
            get { return fapplicant_mobile; }
            set { SetPropertyValue<string>("applicant_mobile", ref fapplicant_mobile, value); }
        }
        rec_Nationality fapplicant_nationality_id;
        [Indexed(Name = @"iapplicant_nationality_id_rec_Applicant")]
        [Association(@"rec_ApplicantReferencesrec_Nationality")]
        public rec_Nationality applicant_nationality_id
        {
            get { return fapplicant_nationality_id; }
            set { SetPropertyValue<rec_Nationality>("applicant_nationality_id", ref fapplicant_nationality_id, value); }
        }
        rec_Marital_Status fapplicant_marital_status_id;
        [Indexed(Name = @"iapplicant_marital_status_id_rec_Applicant")]
        [Association(@"rec_ApplicantReferencesrec_Marital_Status")]
        public rec_Marital_Status applicant_marital_status_id
        {
            get { return fapplicant_marital_status_id; }
            set { SetPropertyValue<rec_Marital_Status>("applicant_marital_status_id", ref fapplicant_marital_status_id, value); }
        }
        rec_Military_Status fapplicant_military_id;
        [Indexed(Name = @"iapplicant_military_id_rec_Applicant")]
        [Association(@"rec_ApplicantReferencesrec_Military_Status")]
        public rec_Military_Status applicant_military_id
        {
            get { return fapplicant_military_id; }
            set { SetPropertyValue<rec_Military_Status>("applicant_military_id", ref fapplicant_military_id, value); }
        }
        DateTime fapplicant_birth_date;
        public DateTime applicant_birth_date
        {
            get { return fapplicant_birth_date; }
            set { SetPropertyValue<DateTime>("applicant_birth_date", ref fapplicant_birth_date, value); }
        }
        rec_Work_Type fapplicant_work_type_id;
        [Indexed(Name = @"iapplicant_work_type_id_rec_Applicant")]
        [Association(@"rec_ApplicantReferencesrec_Work_Type")]
        public rec_Work_Type applicant_work_type_id
        {
            get { return fapplicant_work_type_id; }
            set { SetPropertyValue<rec_Work_Type>("applicant_work_type_id", ref fapplicant_work_type_id, value); }
        }
        double fapplicant_salary;
        public double applicant_salary
        {
            get { return fapplicant_salary; }
            set { SetPropertyValue<double>("applicant_salary", ref fapplicant_salary, value); }
        }
        rec_Industry fapplicant_industry_id;
        [Indexed(Name = @"iapplicant_industry_id_rec_Applicant")]
        [Association(@"rec_ApplicantReferencesrec_Industry")]
        public rec_Industry applicant_industry_id
        {
            get { return fapplicant_industry_id; }
            set { SetPropertyValue<rec_Industry>("applicant_industry_id", ref fapplicant_industry_id, value); }
        }
        rec_Position fapplicant_position_id;
        [Indexed(Name = @"iapplicant_position_id_rec_Applicant")]
        [Association(@"rec_ApplicantReferencesrec_Position")]
        public rec_Position applicant_position_id
        {
            get { return fapplicant_position_id; }
            set { SetPropertyValue<rec_Position>("applicant_position_id", ref fapplicant_position_id, value); }
        }
        bool fapplicant_driving_license;
        public bool applicant_driving_license
        {
            get { return fapplicant_driving_license; }
            set { SetPropertyValue<bool>("applicant_driving_license", ref fapplicant_driving_license, value); }
        }
        string fapplicant_skill;
        [Size(1000)]
        public string applicant_skill
        {
            get { return fapplicant_skill; }
            set { SetPropertyValue<string>("applicant_skill", ref fapplicant_skill, value); }
        }
        string fapplicant_summary;
        [Size(1000)]
        public string applicant_summary
        {
            get { return fapplicant_summary; }
            set { SetPropertyValue<string>("applicant_summary", ref fapplicant_summary, value); }
        }
        string fapplicant_national_id;
        [Size(50)]
        public string applicant_national_id
        {
            get { return fapplicant_national_id; }
            set { SetPropertyValue<string>("applicant_national_id", ref fapplicant_national_id, value); }
        }
        rec_Gender fapplicant_gender_id;
        [Indexed(Name = @"iapplicant_gender_id_rec_Applicant")]
        [Association(@"rec_ApplicantReferencesrec_Gender")]
        public rec_Gender applicant_gender_id
        {
            get { return fapplicant_gender_id; }
            set { SetPropertyValue<rec_Gender>("applicant_gender_id", ref fapplicant_gender_id, value); }
        }
        string fapplicant_address;
        [Size(255)]
        public string applicant_address
        {
            get { return fapplicant_address; }
            set { SetPropertyValue<string>("applicant_address", ref fapplicant_address, value); }
        }
        rec_Applicant_Status fapplicant_rec_applicant_status_id;
        [Indexed(Name = @"iapplicant_rec_applicant_status_id_rec_Applicant")]
        [Association(@"rec_ApplicantReferencesrec_Applicant_Status")]
        public rec_Applicant_Status applicant_rec_applicant_status_id
        {
            get { return fapplicant_rec_applicant_status_id; }
            set { SetPropertyValue<rec_Applicant_Status>("applicant_rec_applicant_status_id", ref fapplicant_rec_applicant_status_id, value); }
        }
        [Association(@"rec_Applicant_CourseReferencesrec_Applicant")]
        public XPCollection<rec_Applicant_Course> rec_Applicant_Courses { get { return GetCollection<rec_Applicant_Course>("rec_Applicant_Courses"); } }
        [Association(@"rec_Applicant_EducationReferencesrec_Applicant")]
        public XPCollection<rec_Applicant_Education> rec_Applicant_Educations { get { return GetCollection<rec_Applicant_Education>("rec_Applicant_Educations"); } }
        [Association(@"rec_Applicant_ExperienceReferencesrec_Applicant")]
        public XPCollection<rec_Applicant_Experience> rec_Applicant_Experiences { get { return GetCollection<rec_Applicant_Experience>("rec_Applicant_Experiences"); } }
        [Association(@"rec_Applicant_ProjectReferencesrec_Applicant")]
        public XPCollection<rec_Applicant_Project> rec_Applicant_Projects { get { return GetCollection<rec_Applicant_Project>("rec_Applicant_Projects"); } }
        [Association(@"rec_Applicant_StudyReferencesrec_Applicant")]
        public XPCollection<rec_Applicant_Study> rec_Applicant_Studys { get { return GetCollection<rec_Applicant_Study>("rec_Applicant_Studys"); } }
        [Association(@"rec_Employer_Order_Detail_CallReferencesrec_Applicant")]
        public XPCollection<rec_Employer_Order_Detail_Call> rec_Employer_Order_Detail_Calls { get { return GetCollection<rec_Employer_Order_Detail_Call>("rec_Employer_Order_Detail_Calls"); } }
        [Association(@"rec_Employer_Order_Detail_Suggest_ApplicatReferencesrec_Applicant")]
        public XPCollection<rec_Employer_Order_Detail_Suggest_Applicat> rec_Employer_Order_Detail_Suggest_Applicats { get { return GetCollection<rec_Employer_Order_Detail_Suggest_Applicat>("rec_Employer_Order_Detail_Suggest_Applicats"); } }
        [Association(@"rec_Applicant_TagReferencesrec_Applicant")]
        public XPCollection<rec_Applicant_Tag> rec_Applicant_Tags { get { return GetCollection<rec_Applicant_Tag>("rec_Applicant_Tags"); } }
    }

}
