//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Applicant_Project : XPLiteObject
    {
        int fapp_prj_id;
        [Key(true)]
        public int app_prj_id
        {
            get { return fapp_prj_id; }
            set { SetPropertyValue<int>("app_prj_id", ref fapp_prj_id, value); }
        }
        rec_Applicant fapp_prj_applicant_id;
        [Association(@"rec_Applicant_ProjectReferencesrec_Applicant")]
        public rec_Applicant app_prj_applicant_id
        {
            get { return fapp_prj_applicant_id; }
            set { SetPropertyValue<rec_Applicant>("app_prj_applicant_id", ref fapp_prj_applicant_id, value); }
        }
        string fapp_prj_title;
        public string app_prj_title
        {
            get { return fapp_prj_title; }
            set { SetPropertyValue<string>("app_prj_title", ref fapp_prj_title, value); }
        }
        string fapp_prj_company_name;
        public string app_prj_company_name
        {
            get { return fapp_prj_company_name; }
            set { SetPropertyValue<string>("app_prj_company_name", ref fapp_prj_company_name, value); }
        }
        string fapp_prj_url;
        public string app_prj_url
        {
            get { return fapp_prj_url; }
            set { SetPropertyValue<string>("app_prj_url", ref fapp_prj_url, value); }
        }
        DateTime fapp_prj_date;
        public DateTime app_prj_date
        {
            get { return fapp_prj_date; }
            set { SetPropertyValue<DateTime>("app_prj_date", ref fapp_prj_date, value); }
        }
        string fapp_prj_description;
        [Size(1000)]
        public string app_prj_description
        {
            get { return fapp_prj_description; }
            set { SetPropertyValue<string>("app_prj_description", ref fapp_prj_description, value); }
        }
    }

}
