//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_DocSrv_Activity : XPLiteObject
    {
        int fDocSrv_activity_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int DocSrv_activity_id
        {
            get { return fDocSrv_activity_id; }
            set { SetPropertyValue<int>("DocSrv_activity_id", ref fDocSrv_activity_id, value); }
        }
        rec_DocSrv_Order_Detail_Srv fdocsrv_order_detail_srv_id;
        [Association(@"rec_DocSrv_ActivityReferencesrec_DocSrv_Order_Detail_Srv")]
        [DevExpress.Xpo.DisplayName(@"Document Service")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_DocSrv_Activity_docsrv_order_detail_srv_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Select Employee")]
        public rec_DocSrv_Order_Detail_Srv docsrv_order_detail_srv_id
        {
            get { return fdocsrv_order_detail_srv_id; }
            set { SetPropertyValue<rec_DocSrv_Order_Detail_Srv>("docsrv_order_detail_srv_id", ref fdocsrv_order_detail_srv_id, value); }
        }
        rec_Activity factivity_id;
        [Association(@"rec_DocSrv_ActivityReferencesrec_Activity")]
        [DevExpress.Xpo.DisplayName(@"Activity")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_DocSrv_Activity_activity_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Select Activity")]
        public rec_Activity activity_id
        {
            get { return factivity_id; }
            set { SetPropertyValue<rec_Activity>("activity_id", ref factivity_id, value); }
        }
        DateTime factivity_date;
        [DevExpress.Xpo.DisplayName(@"Activity Date")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_DocSrv_Activity_activity_date_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Date")]
        public DateTime activity_date
        {
            get { return factivity_date; }
            set { SetPropertyValue<DateTime>("activity_date", ref factivity_date, value); }
        }
        rec_Cash fcash_id;
        [Association(@"rec_DocSrv_ActivityReferencesrec_Cash")]
        [DevExpress.Xpo.DisplayName(@"Cash")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_DocSrv_Activity_cash_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Select Cash")]
        public rec_Cash cash_id
        {
            get { return fcash_id; }
            set { SetPropertyValue<rec_Cash>("cash_id", ref fcash_id, value); }
        }
        double fvalue1;
        [Persistent(@"value")]
        [DevExpress.Xpo.DisplayName(@"Value")]
        public double value1
        {
            get { return fvalue1; }
            set { SetPropertyValue<double>("value1", ref fvalue1, value); }
        }
        double forg_value;
        [DevExpress.Xpo.DisplayName(@"Original Value")]
        public double org_value
        {
            get { return forg_value; }
            set { SetPropertyValue<double>("org_value", ref forg_value, value); }
        }
        Accounting.BusinessObjects.Recruitment.acc_Currency fcurrency_id;
        [DevExpress.Xpo.DisplayName(@"Currency")]
        public Accounting.BusinessObjects.Recruitment.acc_Currency currency_id
        {
            get { return fcurrency_id; }
            set { SetPropertyValue<Accounting.BusinessObjects.Recruitment.acc_Currency>("currency_id", ref fcurrency_id, value); }
        }
        Accounting.BusinessObjects.Recruitment.acc_Journal_Entry fjour_entry_id;
        [DevExpress.Xpo.DisplayName(@"Journal entry")]
        public Accounting.BusinessObjects.Recruitment.acc_Journal_Entry jour_entry_id
        {
            get { return fjour_entry_id; }
            set { SetPropertyValue<Accounting.BusinessObjects.Recruitment.acc_Journal_Entry>("jour_entry_id", ref fjour_entry_id, value); }
        }
        string fvoucher_no;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Voucher No")]
        public string voucher_no
        {
            get { return fvoucher_no; }
            set { SetPropertyValue<string>("voucher_no", ref fvoucher_no, value); }
        }
    }

}
