//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Applicant_Tag : XPLiteObject
    {
        int fapp_tag_id;
        public int app_tag_id
        {
            get { return fapp_tag_id; }
            set { SetPropertyValue<int>("app_tag_id", ref fapp_tag_id, value); }
        }
        int fapp_tag_user_id;
        public int app_tag_user_id
        {
            get { return fapp_tag_user_id; }
            set { SetPropertyValue<int>("app_tag_user_id", ref fapp_tag_user_id, value); }
        }
        DateTime fapp_tag_date_in;
        public DateTime app_tag_date_in
        {
            get { return fapp_tag_date_in; }
            set { SetPropertyValue<DateTime>("app_tag_date_in", ref fapp_tag_date_in, value); }
        }
        public struct CompoundKey1Struct
        {
            [Persistent("app_tag_applicant_id")]
            public int app_tag_applicant_id { get; set; }
            [Persistent("app_tag_tag_id")]
            public int app_tag_tag_id { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
