//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Faculty : XPLiteObject
    {
        int ffaculty_id;
        [Key(true)]
        public int faculty_id
        {
            get { return ffaculty_id; }
            set { SetPropertyValue<int>("faculty_id", ref ffaculty_id, value); }
        }
        string ffaculty_name;
        public string faculty_name
        {
            get { return ffaculty_name; }
            set { SetPropertyValue<string>("faculty_name", ref ffaculty_name, value); }
        }
        [Association(@"rec_Applicant_EducationReferencesrec_Faculty")]
        public XPCollection<rec_Applicant_Education> rec_Applicant_Educations { get { return GetCollection<rec_Applicant_Education>("rec_Applicant_Educations"); } }
    }

}
