//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Activity_Type : XPLiteObject
    {
        int factivity_type_id;
        [Key(true)]
        public int activity_type_id
        {
            get { return factivity_type_id; }
            set { SetPropertyValue<int>("activity_type_id", ref factivity_type_id, value); }
        }
        string factivity_type_name;
        [Size(50)]
        public string activity_type_name
        {
            get { return factivity_type_name; }
            set { SetPropertyValue<string>("activity_type_name", ref factivity_type_name, value); }
        }
        [Association(@"rec_ActivityReferencesrec_Activity_Type")]
        public XPCollection<rec_Activity> rec_Activitys { get { return GetCollection<rec_Activity>("rec_Activitys"); } }
    }

}
