//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Military_Status : XPLiteObject
    {
        int fmilitary_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"Id")]
        public int military_id
        {
            get { return fmilitary_id; }
            set { SetPropertyValue<int>("military_id", ref fmilitary_id, value); }
        }
        string fmilitary_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Military status")]
        [DevExpress.Persistent.Validation.RuleUniqueValue("", DevExpress.Persistent.Validation.DefaultContexts.Save, "Object with the same name exists")]
        public string military_name
        {
            get { return fmilitary_name; }
            set { SetPropertyValue<string>("military_name", ref fmilitary_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Applicants")]
        [Association(@"rec_ApplicantReferencesrec_Military_Status")]
        public XPCollection<rec_Applicant> rec_Applicants { get { return GetCollection<rec_Applicant>("rec_Applicants"); } }
    }

}
