//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Work_Type : XPLiteObject
    {
        int fwork_type_id;
        [Key(true)]
        public int work_type_id
        {
            get { return fwork_type_id; }
            set { SetPropertyValue<int>("work_type_id", ref fwork_type_id, value); }
        }
        string fwork_type_name;
        public string work_type_name
        {
            get { return fwork_type_name; }
            set { SetPropertyValue<string>("work_type_name", ref fwork_type_name, value); }
        }
        [Association(@"rec_ApplicantReferencesrec_Work_Type")]
        public XPCollection<rec_Applicant> rec_Applicants { get { return GetCollection<rec_Applicant>("rec_Applicants"); } }
        [Association(@"rec_Applicant_ExperienceReferencesrec_Work_Type")]
        public XPCollection<rec_Applicant_Experience> rec_Applicant_Experiences { get { return GetCollection<rec_Applicant_Experience>("rec_Applicant_Experiences"); } }
    }

}
