//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Employer_Order_Interview : XPLiteObject
    {
        int frec_employer_order_interview_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"Id")]
        public int rec_employer_order_interview_id
        {
            get { return frec_employer_order_interview_id; }
            set { SetPropertyValue<int>("rec_employer_order_interview_id", ref frec_employer_order_interview_id, value); }
        }
        rec_Employer_Order frec_employer_order_id;
        [Indexed(Name = @"irec_employer_order_detail_suggest_applicat_rec_suggest_applicat_source_id_rec_Employer_Order_Detail_Suggest_Applicat")]
        [Association(@"rec_Employer_Order_InterviewReferencesrec_Employer_Order")]
        [DevExpress.Xpo.DisplayName(@"b")]
        public rec_Employer_Order rec_employer_order_id
        {
            get { return frec_employer_order_id; }
            set { SetPropertyValue<rec_Employer_Order>("rec_employer_order_id", ref frec_employer_order_id, value); }
        }
        DateTime frec_employer_order_interview_date;
        [DevExpress.Xpo.DisplayName(@"Interview date")]
        public DateTime rec_employer_order_interview_date
        {
            get { return frec_employer_order_interview_date; }
            set { SetPropertyValue<DateTime>("rec_employer_order_interview_date", ref frec_employer_order_interview_date, value); }
        }
        string frec_employer_order_interview_note;
        [Size(1000)]
        [DevExpress.Xpo.DisplayName(@"Note")]
        public string rec_employer_order_interview_note
        {
            get { return frec_employer_order_interview_note; }
            set { SetPropertyValue<string>("rec_employer_order_interview_note", ref frec_employer_order_interview_note, value); }
        }
    }

}
