//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Employee_Activity : XPLiteObject
    {
        int femployee_activity_id;
        [Key(true)]
        public int employee_activity_id
        {
            get { return femployee_activity_id; }
            set { SetPropertyValue<int>("employee_activity_id", ref femployee_activity_id, value); }
        }
        int femployee_id;
        public int employee_id
        {
            get { return femployee_id; }
            set { SetPropertyValue<int>("employee_id", ref femployee_id, value); }
        }
        int factivity_id;
        public int activity_id
        {
            get { return factivity_id; }
            set { SetPropertyValue<int>("activity_id", ref factivity_id, value); }
        }
        DateTime factivity_date;
        public DateTime activity_date
        {
            get { return factivity_date; }
            set { SetPropertyValue<DateTime>("activity_date", ref factivity_date, value); }
        }
        int fcash_id;
        public int cash_id
        {
            get { return fcash_id; }
            set { SetPropertyValue<int>("cash_id", ref fcash_id, value); }
        }
        double fvalue1;
        [Persistent(@"value")]
        public double value1
        {
            get { return fvalue1; }
            set { SetPropertyValue<double>("value1", ref fvalue1, value); }
        }
        double forg_value;
        public double org_value
        {
            get { return forg_value; }
            set { SetPropertyValue<double>("org_value", ref forg_value, value); }
        }
        int fcurrency_id;
        public int currency_id
        {
            get { return fcurrency_id; }
            set { SetPropertyValue<int>("currency_id", ref fcurrency_id, value); }
        }
        int fjour_entry_id;
        public int jour_entry_id
        {
            get { return fjour_entry_id; }
            set { SetPropertyValue<int>("jour_entry_id", ref fjour_entry_id, value); }
        }
        string fvoucher_no;
        [Size(50)]
        public string voucher_no
        {
            get { return fvoucher_no; }
            set { SetPropertyValue<string>("voucher_no", ref fvoucher_no, value); }
        }
    }

}
