//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Tag : XPLiteObject
    {
        int ftag_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"Id")]
        public int tag_id
        {
            get { return ftag_id; }
            set { SetPropertyValue<int>("tag_id", ref ftag_id, value); }
        }
        string ftag_name;
        [DevExpress.Xpo.DisplayName(@"Tag name")]
        [DevExpress.Persistent.Validation.RuleUniqueValue("", DevExpress.Persistent.Validation.DefaultContexts.Save, "Object with the same name exists")]
        public string tag_name
        {
            get { return ftag_name; }
            set { SetPropertyValue<string>("tag_name", ref ftag_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Applicant Tags")]
        [Association(@"rec_Applicant_TagReferencesrec_Tag")]
        public XPCollection<rec_Applicant_Tag> rec_Applicant_Tags { get { return GetCollection<rec_Applicant_Tag>("rec_Applicant_Tags"); } }
    }

}
