//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Applicant_Tag : XPLiteObject
    {
        int fapp_tag_id;
        [Indexed(Name = @"rec_Applicant_Tag.app_tag_id", Unique = true)]
        [Key(true)]
        public int app_tag_id
        {
            get { return fapp_tag_id; }
            set { SetPropertyValue<int>("app_tag_id", ref fapp_tag_id, value); }
        }
        rec_Applicant fapp_tag_applicant_id;
        [Indexed(Name = @"rec_Applicant_Tag.app_tag_applicant_id")]
        [Association(@"rec_Applicant_TagReferencesrec_Applicant")]
        public rec_Applicant app_tag_applicant_id
        {
            get { return fapp_tag_applicant_id; }
            set { SetPropertyValue<rec_Applicant>("app_tag_applicant_id", ref fapp_tag_applicant_id, value); }
        }
        rec_Tag fapp_tag_tag_id;
        [Indexed(Name = @"rec_Applicant_Tag.app_tag_tag_id")]
        [Association(@"rec_Applicant_TagReferencesrec_Tag")]
        public rec_Tag app_tag_tag_id
        {
            get { return fapp_tag_tag_id; }
            set { SetPropertyValue<rec_Tag>("app_tag_tag_id", ref fapp_tag_tag_id, value); }
        }
    }

}
