//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_DocSrv_Order : XPLiteObject
    {
        int fdocsrv_order_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int docsrv_order_id
        {
            get { return fdocsrv_order_id; }
            set { SetPropertyValue<int>("docsrv_order_id", ref fdocsrv_order_id, value); }
        }
        DateTime forder_date;
        [DevExpress.Xpo.DisplayName(@"Order Date")]
        public DateTime order_date
        {
            get { return forder_date; }
            set { SetPropertyValue<DateTime>("order_date", ref forder_date, value); }
        }
        string fperson_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Person Name")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_DocSrv_Order_person_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Person Name")]
        public string person_name
        {
            get { return fperson_name; }
            set { SetPropertyValue<string>("person_name", ref fperson_name, value); }
        }
        string fperson_mobile;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Person Mobile")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_DocSrv_Order_person_mobile_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Person Mobil")]
        public string person_mobile
        {
            get { return fperson_mobile; }
            set { SetPropertyValue<string>("person_mobile", ref fperson_mobile, value); }
        }
        string fperson_phone;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Person Phone")]
        public string person_phone
        {
            get { return fperson_phone; }
            set { SetPropertyValue<string>("person_phone", ref fperson_phone, value); }
        }
        string fnotes;
        [Size(1000)]
        [DevExpress.Xpo.DisplayName(@"Notes")]
        public string notes
        {
            get { return fnotes; }
            set { SetPropertyValue<string>("notes", ref fnotes, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Document Service Order Details")]
        [Association(@"rec_DocSrv_Order_DetailReferencesrec_DocSrv_Order")]
        public XPCollection<rec_DocSrv_Order_Detail> rec_DocSrv_Order_Details { get { return GetCollection<rec_DocSrv_Order_Detail>("rec_DocSrv_Order_Details"); } }
    }

}
