//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_DocSrv_Type : XPLiteObject
    {
        int fdocsrv_type_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int docsrv_type_id
        {
            get { return fdocsrv_type_id; }
            set { SetPropertyValue<int>("docsrv_type_id", ref fdocsrv_type_id, value); }
        }
        string fdocsrv_type_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Service Name")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_DocSrv_Type_docsrv_type_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Service Name")]
        public string docsrv_type_name
        {
            get { return fdocsrv_type_name; }
            set { SetPropertyValue<string>("docsrv_type_name", ref fdocsrv_type_name, value); }
        }
        double fdocsrv_type_price;
        [DevExpress.Xpo.DisplayName(@"Service Price")]
        [DevExpress.Persistent.Validation.RuleRequiredField("rec_DocSrv_Type_docsrv_type_price_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Price")]
        public double docsrv_type_price
        {
            get { return fdocsrv_type_price; }
            set { SetPropertyValue<double>("docsrv_type_price", ref fdocsrv_type_price, value); }
        }
        string fnotes;
        [Size(1000)]
        [DevExpress.Xpo.DisplayName(@"Notes")]
        public string notes
        {
            get { return fnotes; }
            set { SetPropertyValue<string>("notes", ref fnotes, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Document Service Orders")]
        [Association(@"rec_DocSrv_Order_Detail_SrvReferencesrec_DocSrv_Type")]
        public XPCollection<rec_DocSrv_Order_Detail_Srv> rec_DocSrv_Order_Detail_Srvs { get { return GetCollection<rec_DocSrv_Order_Detail_Srv>("rec_DocSrv_Order_Detail_Srvs"); } }
    }

}
