//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Study_Grade : XPLiteObject
    {
        int fstudy_grade_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"Id")]
        public int study_grade_id
        {
            get { return fstudy_grade_id; }
            set { SetPropertyValue<int>("study_grade_id", ref fstudy_grade_id, value); }
        }
        string fstudy_grade_name;
        [DevExpress.Xpo.DisplayName(@"Grade name")]
        [DevExpress.Persistent.Validation.RuleUniqueValue("", DevExpress.Persistent.Validation.DefaultContexts.Save, "Object with the same name exists")]
        public string study_grade_name
        {
            get { return fstudy_grade_name; }
            set { SetPropertyValue<string>("study_grade_name", ref fstudy_grade_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Applicant Educations")]
        [Association(@"rec_Applicant_EducationReferencesrec_Study_Grade")]
        public XPCollection<rec_Applicant_Education> rec_Applicant_Educations { get { return GetCollection<rec_Applicant_Education>("rec_Applicant_Educations"); } }
    }

}
