//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Applicant_Study : XPLiteObject
    {
        int fapp_grd_id;
        [Key]
        public int app_grd_id
        {
            get { return fapp_grd_id; }
            set { SetPropertyValue<int>("app_grd_id", ref fapp_grd_id, value); }
        }
        rec_Applicant fapp_grd_applicant_id;
        [Association(@"rec_Applicant_StudyReferencesrec_Applicant")]
        public rec_Applicant app_grd_applicant_id
        {
            get { return fapp_grd_applicant_id; }
            set { SetPropertyValue<rec_Applicant>("app_grd_applicant_id", ref fapp_grd_applicant_id, value); }
        }
        rec_Degree fapp_grd_degree_id;
        [Association(@"rec_Applicant_StudyReferencesrec_Degree")]
        public rec_Degree app_grd_degree_id
        {
            get { return fapp_grd_degree_id; }
            set { SetPropertyValue<rec_Degree>("app_grd_degree_id", ref fapp_grd_degree_id, value); }
        }
        string fdegree_id_field_of_research;
        public string degree_id_field_of_research
        {
            get { return fdegree_id_field_of_research; }
            set { SetPropertyValue<string>("degree_id_field_of_research", ref fdegree_id_field_of_research, value); }
        }
        int fapp_grd_grade_year;
        public int app_grd_grade_year
        {
            get { return fapp_grd_grade_year; }
            set { SetPropertyValue<int>("app_grd_grade_year", ref fapp_grd_grade_year, value); }
        }
        rec_Study_Grade fapp_grd_study_grade_id;
        [Association(@"rec_Applicant_StudyReferencesrec_Study_Grade")]
        public rec_Study_Grade app_grd_study_grade_id
        {
            get { return fapp_grd_study_grade_id; }
            set { SetPropertyValue<rec_Study_Grade>("app_grd_study_grade_id", ref fapp_grd_study_grade_id, value); }
        }
        int fapp_grd_user_id;
        public int app_grd_user_id
        {
            get { return fapp_grd_user_id; }
            set { SetPropertyValue<int>("app_grd_user_id", ref fapp_grd_user_id, value); }
        }
        DateTime fapp_grd_date_in;
        public DateTime app_grd_date_in
        {
            get { return fapp_grd_date_in; }
            set { SetPropertyValue<DateTime>("app_grd_date_in", ref fapp_grd_date_in, value); }
        }
    }

}
