//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Applicant_Langauge : XPLiteObject
    {
        int fapp_lang_id;
        [Key(true)]
        public int app_lang_id
        {
            get { return fapp_lang_id; }
            set { SetPropertyValue<int>("app_lang_id", ref fapp_lang_id, value); }
        }
        rec_Applicant fapp_lang_applicant_id;
        [Indexed(Name = @"iapp_lang_applicant_id_rec_Applicant_Langauge")]
        [Association(@"rec_Applicant_LangaugeReferencesrec_Applicant")]
        public rec_Applicant app_lang_applicant_id
        {
            get { return fapp_lang_applicant_id; }
            set { SetPropertyValue<rec_Applicant>("app_lang_applicant_id", ref fapp_lang_applicant_id, value); }
        }
        rec_Langauge fapp_lang_langauge_id;
        [Indexed(Name = @"iapp_lang_langauge_id_rec_Applicant_Langauge")]
        [Association(@"rec_Applicant_LangaugeReferencesrec_Langauge")]
        public rec_Langauge app_lang_langauge_id
        {
            get { return fapp_lang_langauge_id; }
            set { SetPropertyValue<rec_Langauge>("app_lang_langauge_id", ref fapp_lang_langauge_id, value); }
        }
        rec_Langauge_Level frec_lang_level_id;
        [Association(@"rec_Applicant_LangaugeReferencesrec_Langauge_Level")]
        public rec_Langauge_Level rec_lang_level_id
        {
            get { return frec_lang_level_id; }
            set { SetPropertyValue<rec_Langauge_Level>("rec_lang_level_id", ref frec_lang_level_id, value); }
        }
    }

}
