//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    public partial class rec_Applicant_Industry : XPLiteObject
    {
        int fapp_indus_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"Id")]
        public int app_indus_id
        {
            get { return fapp_indus_id; }
            set { SetPropertyValue<int>("app_indus_id", ref fapp_indus_id, value); }
        }
        rec_Applicant fapp_indus_applicant_id;
        [Association(@"rec_Applicant_IndustryReferencesrec_Applicant")]
        [DevExpress.Xpo.DisplayName(@"Applicant")]
        public rec_Applicant app_indus_applicant_id
        {
            get { return fapp_indus_applicant_id; }
            set { SetPropertyValue<rec_Applicant>("app_indus_applicant_id", ref fapp_indus_applicant_id, value); }
        }
        rec_Industry fapp_indus_industry_id;
        [Association(@"rec_Applicant_IndustryReferencesrec_Industry")]
        [DevExpress.Xpo.DisplayName(@"Industry")]
        public rec_Industry app_indus_industry_id
        {
            get { return fapp_indus_industry_id; }
            set { SetPropertyValue<rec_Industry>("app_indus_industry_id", ref fapp_indus_industry_id, value); }
        }
    }

}
