//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{

    [NonPersistent]
    public partial class sp_Activity_03Result
    {
        public int employer_id { get; set; }
        public string employer_owner_name { get; set; }
        public string employer_company_name { get; set; }
        public double BudgetRevenue { get; set; }
        public double ActualRevenue { get; set; }
        public double Expenses { get; set; }
        public string Person_Name { get; set; }
    }

}
