//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Module.BusinessObjects.Recruitment
{
    public static class SprocHelper
    {
        public static DevExpress.Xpo.DB.SelectedData Execsp_ClearDB(Session session)
        {
            return session.ExecuteSproc("sp_ClearDB");
        }
        public static DevExpress.Xpo.DB.SelectedData Execsp_Activity_01(Session session, DateTime StartDate, DateTime EndDate, int employer_id)
        {
            return session.ExecuteSproc("sp_Activity_01", new OperandValue(StartDate), new OperandValue(EndDate), new OperandValue(employer_id));
        }
        public static System.Collections.Generic.ICollection<sp_Activity_01Result> Execsp_Activity_01IntoObjects(Session session, DateTime StartDate, DateTime EndDate, int employer_id)
        {
            return session.GetObjectsFromSproc<sp_Activity_01Result>("sp_Activity_01", new OperandValue(StartDate), new OperandValue(EndDate), new OperandValue(employer_id));
        }
        public static XPDataView Execsp_Activity_01IntoDataView(Session session, DateTime StartDate, DateTime EndDate, int employer_id)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("sp_Activity_01", new OperandValue(StartDate), new OperandValue(EndDate), new OperandValue(employer_id));
            return new XPDataView(session.Dictionary, session.GetClassInfo(typeof(sp_Activity_01Result)), sprocData);
        }
        public static void Execsp_Activity_01IntoDataView(XPDataView dataView, Session session, DateTime StartDate, DateTime EndDate, int employer_id)
        {
            DevExpress.Xpo.DB.SelectedData sprocData = session.ExecuteSproc("sp_Activity_01", new OperandValue(StartDate), new OperandValue(EndDate), new OperandValue(employer_id));
            dataView.PopulateProperties(session.GetClassInfo(typeof(sp_Activity_01Result)));
            dataView.LoadData(sprocData);
        }
    }
}
