//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Accounting.BusinessObjects.Recruitment
{

    public partial class acc_Account_Type : XPLiteObject
    {
        int faccount_type_id;
        [Key(true)]
        public int account_type_id
        {
            get { return faccount_type_id; }
            set { SetPropertyValue<int>("account_type_id", ref faccount_type_id, value); }
        }
        string faccount_type_name;
        [Size(50)]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Account_Type_account_type_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Name")]
        public string account_type_name
        {
            get { return faccount_type_name; }
            set { SetPropertyValue<string>("account_type_name", ref faccount_type_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Accounts")]
        [Association(@"acc_AccountReferencesacc_Account_Type")]
        public XPCollection<acc_Account> acc_Accounts { get { return GetCollection<acc_Account>("acc_Accounts"); } }
    }

}
