//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Accounting.BusinessObjects.Recruitment
{

    public partial class acc_Account : XPLiteObject
    {
        int faccount_id;
        [Key(true)]
        public int account_id
        {
            get { return faccount_id; }
            set { SetPropertyValue<int>("account_id", ref faccount_id, value); }
        }
        string faccount_name;
        [Size(50)]
        public string account_name
        {
            get { return faccount_name; }
            set { SetPropertyValue<string>("account_name", ref faccount_name, value); }
        }
        acc_Account fparent_account_id;
        [Association(@"acc_AccountReferencesacc_Account")]
        public acc_Account parent_account_id
        {
            get { return fparent_account_id; }
            set { SetPropertyValue<acc_Account>("parent_account_id", ref fparent_account_id, value); }
        }
        acc_Account_Type faccount_type_id;
        [Indexed(Name = @"iaccount_type_id_acc_Account")]
        [Association(@"acc_AccountReferencesacc_Account_Type")]
        public acc_Account_Type account_type_id
        {
            get { return faccount_type_id; }
            set { SetPropertyValue<acc_Account_Type>("account_type_id", ref faccount_type_id, value); }
        }
        acc_Nature facc_nature_id;
        [Indexed(Name = @"iacc_nature_id_acc_Account")]
        [Association(@"acc_AccountReferencesacc_Nature")]
        public acc_Nature acc_nature_id
        {
            get { return facc_nature_id; }
            set { SetPropertyValue<acc_Nature>("acc_nature_id", ref facc_nature_id, value); }
        }
        bool fclosed;
        public bool closed
        {
            get { return fclosed; }
            set { SetPropertyValue<bool>("closed", ref fclosed, value); }
        }
        [Association(@"acc_AccountReferencesacc_Account")]
        public XPCollection<acc_Account> acc_AccountCollection { get { return GetCollection<acc_Account>("acc_AccountCollection"); } }
        [Association(@"acc_Journal_Entry_DetailReferencesacc_Account")]
        public XPCollection<acc_Journal_Entry_Detail> acc_Journal_Entry_Details { get { return GetCollection<acc_Journal_Entry_Detail>("acc_Journal_Entry_Details"); } }
    }

}
