//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Accounting.BusinessObjects.Recruitment
{

    public partial class acc_Bank : XPLiteObject
    {
        int fbank_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int bank_id
        {
            get { return fbank_id; }
            set { SetPropertyValue<int>("bank_id", ref fbank_id, value); }
        }
        string fbank_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Bank name")]
        public string bank_name
        {
            get { return fbank_name; }
            set { SetPropertyValue<string>("bank_name", ref fbank_name, value); }
        }
        string fbank_acc_number;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Account number")]
        public string bank_acc_number
        {
            get { return fbank_acc_number; }
            set { SetPropertyValue<string>("bank_acc_number", ref fbank_acc_number, value); }
        }
        string fbank_acc_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Account name")]
        public string bank_acc_name
        {
            get { return fbank_acc_name; }
            set { SetPropertyValue<string>("bank_acc_name", ref fbank_acc_name, value); }
        }
        string fbank_address;
        [DevExpress.Xpo.DisplayName(@"Address")]
        public string bank_address
        {
            get { return fbank_address; }
            set { SetPropertyValue<string>("bank_address", ref fbank_address, value); }
        }
        string fbank_phone;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Phone")]
        public string bank_phone
        {
            get { return fbank_phone; }
            set { SetPropertyValue<string>("bank_phone", ref fbank_phone, value); }
        }
        string fbank_fax;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Fax")]
        public string bank_fax
        {
            get { return fbank_fax; }
            set { SetPropertyValue<string>("bank_fax", ref fbank_fax, value); }
        }
        string fbank_note;
        [Size(500)]
        [DevExpress.Xpo.DisplayName(@"Note")]
        public string bank_note
        {
            get { return fbank_note; }
            set { SetPropertyValue<string>("bank_note", ref fbank_note, value); }
        }
        acc_Account fbank_acc_id;
        [Indexed(Name = @"ibank_acc_id_acc_Bank")]
        [Association(@"acc_BankReferencesacc_Account")]
        [DevExpress.Xpo.DisplayName(@"Account")]
        public acc_Account bank_acc_id
        {
            get { return fbank_acc_id; }
            set { SetPropertyValue<acc_Account>("bank_acc_id", ref fbank_acc_id, value); }
        }
    }

}
