//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Accounting.BusinessObjects.Recruitment
{

    public partial class acc_Currency : XPLiteObject
    {
        int fcurrency_id;
        [Key(true)]
        public int currency_id
        {
            get { return fcurrency_id; }
            set { SetPropertyValue<int>("currency_id", ref fcurrency_id, value); }
        }
        string fcurrency_name;
        [Size(50)]
        public string currency_name
        {
            get { return fcurrency_name; }
            set { SetPropertyValue<string>("currency_name", ref fcurrency_name, value); }
        }
    }

}
