//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Accounting.BusinessObjects.Recruitment
{

    public partial class acc_Account_Category : XPLiteObject
    {
        int faccount_category_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int account_category_id
        {
            get { return faccount_category_id; }
            set { SetPropertyValue<int>("account_category_id", ref faccount_category_id, value); }
        }
        string faccount_category_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Category Name")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Account_Category_account_category_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Category Name")]
        public string account_category_name
        {
            get { return faccount_category_name; }
            set { SetPropertyValue<string>("account_category_name", ref faccount_category_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Category Details")]
        [Association(@"acc_Account_Category_DetailReferencesacc_Account_Category")]
        public XPCollection<acc_Account_Category_Detail> acc_Account_Category_Details { get { return GetCollection<acc_Account_Category_Detail>("acc_Account_Category_Details"); } }
    }

}
