//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Accounting.BusinessObjects.Recruitment
{

    public partial class acc_Journal_Entry : XPLiteObject
    {
        int fjour_entry_id;
        [Key(true)]
        public int jour_entry_id
        {
            get { return fjour_entry_id; }
            set { SetPropertyValue<int>("jour_entry_id", ref fjour_entry_id, value); }
        }
        DateTime fentry_date;
        public DateTime entry_date
        {
            get { return fentry_date; }
            set { SetPropertyValue<DateTime>("entry_date", ref fentry_date, value); }
        }
        acc_Year fyear_id;
        [Association(@"acc_Journal_EntryReferencesacc_Year")]
        public acc_Year year_id
        {
            get { return fyear_id; }
            set { SetPropertyValue<acc_Year>("year_id", ref fyear_id, value); }
        }
        bool fclosed;
        public bool closed
        {
            get { return fclosed; }
            set { SetPropertyValue<bool>("closed", ref fclosed, value); }
        }
        string fvoucher_no;
        [Size(50)]
        public string voucher_no
        {
            get { return fvoucher_no; }
            set { SetPropertyValue<string>("voucher_no", ref fvoucher_no, value); }
        }
        string fdescription;
        [Size(500)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
        string fentry_text;
        public string entry_text
        {
            get { return fentry_text; }
            set { SetPropertyValue<string>("entry_text", ref fentry_text, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Journal Entry Details")]
        [Association(@"acc_Journal_Entry_DetailReferencesacc_Journal_Entry")]
        public XPCollection<acc_Journal_Entry_Detail> acc_Journal_Entry_Details { get { return GetCollection<acc_Journal_Entry_Detail>("acc_Journal_Entry_Details"); } }
    }

}
