//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Accounting.BusinessObjects.Recruitment
{

    public partial class acc_Year : XPLiteObject
    {
        int fyear_id;
        [Key(true)]
        public int year_id
        {
            get { return fyear_id; }
            set { SetPropertyValue<int>("year_id", ref fyear_id, value); }
        }
        string fyear_name;
        [Size(50)]
        public string year_name
        {
            get { return fyear_name; }
            set { SetPropertyValue<string>("year_name", ref fyear_name, value); }
        }
        DateTime fyear_start_date;
        public DateTime year_start_date
        {
            get { return fyear_start_date; }
            set { SetPropertyValue<DateTime>("year_start_date", ref fyear_start_date, value); }
        }
        DateTime fyear_end_date;
        public DateTime year_end_date
        {
            get { return fyear_end_date; }
            set { SetPropertyValue<DateTime>("year_end_date", ref fyear_end_date, value); }
        }
        [Association(@"acc_Journal_EntryReferencesacc_Year")]
        public XPCollection<acc_Journal_Entry> acc_Journal_Entrys { get { return GetCollection<acc_Journal_Entry>("acc_Journal_Entrys"); } }
    }

}
