//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Accounting.BusinessObjects.Recruitment
{

    public partial class acc_Journal_Entry_Detail : XPLiteObject
    {
        int fjour_entry_detail_id;
        [Key(true)]
        public int jour_entry_detail_id
        {
            get { return fjour_entry_detail_id; }
            set { SetPropertyValue<int>("jour_entry_detail_id", ref fjour_entry_detail_id, value); }
        }
        acc_Journal_Entry fjour_entry_id;
        [Association(@"acc_Journal_Entry_DetailReferencesacc_Journal_Entry")]
        public acc_Journal_Entry jour_entry_id
        {
            get { return fjour_entry_id; }
            set { SetPropertyValue<acc_Journal_Entry>("jour_entry_id", ref fjour_entry_id, value); }
        }
        acc_Account faccount_id;
        [Association(@"acc_Journal_Entry_DetailReferencesacc_Account")]
        public acc_Account account_id
        {
            get { return faccount_id; }
            set { SetPropertyValue<acc_Account>("account_id", ref faccount_id, value); }
        }
        double fdebit;
        public double debit
        {
            get { return fdebit; }
            set { SetPropertyValue<double>("debit", ref fdebit, value); }
        }
        double fcredit;
        public double credit
        {
            get { return fcredit; }
            set { SetPropertyValue<double>("credit", ref fcredit, value); }
        }
        string fentry_text;
        public string entry_text
        {
            get { return fentry_text; }
            set { SetPropertyValue<string>("entry_text", ref fentry_text, value); }
        }
        string fdescription;
        [Size(500)]
        public string description
        {
            get { return fdescription; }
            set { SetPropertyValue<string>("description", ref fdescription, value); }
        }
    }

}
