//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Accounting.BusinessObjects.Recruitment
{

    public partial class acc_Account_Category_Detail : XPLiteObject
    {
        int faccount_category_detail_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int account_category_detail_id
        {
            get { return faccount_category_detail_id; }
            set { SetPropertyValue<int>("account_category_detail_id", ref faccount_category_detail_id, value); }
        }
        acc_Account_Category faccount_category_id;
        [Association(@"acc_Account_Category_DetailReferencesacc_Account_Category")]
        [DevExpress.Xpo.DisplayName(@"Category")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Account_Category_Detail_account_category_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Select Category")]
        public acc_Account_Category account_category_id
        {
            get { return faccount_category_id; }
            set { SetPropertyValue<acc_Account_Category>("account_category_id", ref faccount_category_id, value); }
        }
        acc_Account faccount_id;
        [Association(@"acc_Account_Category_DetailReferencesacc_Account")]
        [DevExpress.Xpo.DisplayName(@"Account")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Account_Category_Detail_account_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Select An Account")]
        public acc_Account account_id
        {
            get { return faccount_id; }
            set { SetPropertyValue<acc_Account>("account_id", ref faccount_id, value); }
        }
    }

}
