//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Accounting.BusinessObjects.Recruitment
{

    public partial class acc_Account : XPLiteObject
    {
        int faccount_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int account_id
        {
            get { return faccount_id; }
            set { SetPropertyValue<int>("account_id", ref faccount_id, value); }
        }
        string faccount_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Account name")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Account_account_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Account Name")]
        public string account_name
        {
            get { return faccount_name; }
            set { SetPropertyValue<string>("account_name", ref faccount_name, value); }
        }
        acc_Account fparent_account_id;
        [Indexed(Name = @"iparent_account_id_acc_Account")]
        [Association(@"acc_AccountReferencesacc_Account")]
        [DevExpress.Xpo.DisplayName(@"Parent account")]
        public acc_Account parent_account_id
        {
            get { return fparent_account_id; }
            set { SetPropertyValue<acc_Account>("parent_account_id", ref fparent_account_id, value); }
        }
        acc_Account_Type faccount_type_id;
        [Indexed(Name = @"iaccount_type_id_acc_Account")]
        [Association(@"acc_AccountReferencesacc_Account_Type")]
        [DevExpress.Xpo.DisplayName(@"Account type")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Account_account_type_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Account Type")]
        public acc_Account_Type account_type_id
        {
            get { return faccount_type_id; }
            set { SetPropertyValue<acc_Account_Type>("account_type_id", ref faccount_type_id, value); }
        }
        acc_Nature facc_nature_id;
        [Indexed(Name = @"iacc_nature_id_acc_Account")]
        [Association(@"acc_AccountReferencesacc_Nature")]
        [DevExpress.Xpo.DisplayName(@"Account nature")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Account_acc_nature_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Account Nature")]
        public acc_Nature acc_nature_id
        {
            get { return facc_nature_id; }
            set { SetPropertyValue<acc_Nature>("acc_nature_id", ref facc_nature_id, value); }
        }
        bool fclosed;
        [DevExpress.Xpo.DisplayName(@"Close account")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Account_closed_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Closed Account")]
        public bool closed
        {
            get { return fclosed; }
            set { SetPropertyValue<bool>("closed", ref fclosed, value); }
        }
        string faccount_code;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Account code")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Account_account_code_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Account code must not be empty")]
        public string account_code
        {
            get { return faccount_code; }
            set { SetPropertyValue<string>("account_code", ref faccount_code, value); }
        }
        double faccount_fees;
        [DevExpress.Xpo.DisplayName(@"Fees")]
        public double account_fees
        {
            get { return faccount_fees; }
            set { SetPropertyValue<double>("account_fees", ref faccount_fees, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Child Accounts")]
        [Association(@"acc_AccountReferencesacc_Account")]
        public XPCollection<acc_Account> acc_AccountCollection { get { return GetCollection<acc_Account>("acc_AccountCollection"); } }
        [DevExpress.Xpo.DisplayName(@"Journal Entries")]
        [Association(@"acc_Journal_Entry_DetailReferencesacc_Account")]
        public XPCollection<acc_Journal_Entry_Detail> acc_Journal_Entry_Details { get { return GetCollection<acc_Journal_Entry_Detail>("acc_Journal_Entry_Details"); } }
        [DevExpress.Xpo.DisplayName(@"Opening Balances")]
        [Association(@"acc_Opening_BalanceReferencesacc_Account")]
        public XPCollection<acc_Opening_Balance> acc_Opening_Balances { get { return GetCollection<acc_Opening_Balance>("acc_Opening_Balances"); } }
        [DevExpress.Xpo.DisplayName(@"Category Details")]
        [Association(@"acc_Account_Category_DetailReferencesacc_Account")]
        public XPCollection<acc_Account_Category_Detail> acc_Account_Category_Details { get { return GetCollection<acc_Account_Category_Detail>("acc_Account_Category_Details"); } }
        [DevExpress.Xpo.DisplayName(@"Banks")]
        [Association(@"acc_BankReferencesacc_Account")]
        public XPCollection<acc_Bank> acc_Banks { get { return GetCollection<acc_Bank>("acc_Banks"); } }
    }

}
