//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Accounting.BusinessObjects.Recruitment
{

    public partial class acc_CostCenter : XPLiteObject
    {
        int fcostcenter_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int costcenter_id
        {
            get { return fcostcenter_id; }
            set { SetPropertyValue<int>("costcenter_id", ref fcostcenter_id, value); }
        }
        string fcostcenter_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Cost center name")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_CostCenter_costcenter_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter A Name")]
        public string costcenter_name
        {
            get { return fcostcenter_name; }
            set { SetPropertyValue<string>("costcenter_name", ref fcostcenter_name, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Journal Entry Details")]
        [Association(@"acc_Journal_Entry_DetailReferencesacc_CostCenter")]
        public XPCollection<acc_Journal_Entry_Detail> acc_Journal_Entry_Details { get { return GetCollection<acc_Journal_Entry_Detail>("acc_Journal_Entry_Details"); } }
    }

}
