//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Accounting.BusinessObjects.Recruitment
{

    public partial class acc_Period : XPLiteObject
    {
        int fperiod_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int period_id
        {
            get { return fperiod_id; }
            set { SetPropertyValue<int>("period_id", ref fperiod_id, value); }
        }
        string fperiod_name;
        [Size(50)]
        [DevExpress.Xpo.DisplayName(@"Period name")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Period_period_name_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Period Name")]
        public string period_name
        {
            get { return fperiod_name; }
            set { SetPropertyValue<string>("period_name", ref fperiod_name, value); }
        }
        acc_Year fyear_id;
        [Association(@"acc_PeriodReferencesacc_Year")]
        [DevExpress.Xpo.DisplayName(@"Piscal year")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Period_year_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Select Fiscal Year")]
        public acc_Year year_id
        {
            get { return fyear_id; }
            set { SetPropertyValue<acc_Year>("year_id", ref fyear_id, value); }
        }
        DateTime fstart_date;
        [DevExpress.Xpo.DisplayName(@"Start date")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Period_start_date_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter Start Date")]
        public DateTime start_date
        {
            get { return fstart_date; }
            set { SetPropertyValue<DateTime>("start_date", ref fstart_date, value); }
        }
        DateTime fend_date;
        [DevExpress.Xpo.DisplayName(@"End date")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Period_end_date_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter End Date")]
        public DateTime end_date
        {
            get { return fend_date; }
            set { SetPropertyValue<DateTime>("end_date", ref fend_date, value); }
        }
        bool fclosed;
        [DevExpress.Xpo.DisplayName(@"Close period")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Period_closed_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Choose To Close")]
        public bool closed
        {
            get { return fclosed; }
            set { SetPropertyValue<bool>("closed", ref fclosed, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Journal Entries")]
        [Association(@"acc_Journal_EntryReferencesacc_Period")]
        public XPCollection<acc_Journal_Entry> acc_Journal_Entrys { get { return GetCollection<acc_Journal_Entry>("acc_Journal_Entrys"); } }
    }

}
