//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Accounting.BusinessObjects.Recruitment
{

    public partial class acc_Opening_Balance : XPLiteObject
    {
        int fopening_balance_id;
        [Key(true)]
        [DevExpress.Xpo.DisplayName(@"ID")]
        public int opening_balance_id
        {
            get { return fopening_balance_id; }
            set { SetPropertyValue<int>("opening_balance_id", ref fopening_balance_id, value); }
        }
        acc_Account faccount_id;
        [Association(@"acc_Opening_BalanceReferencesacc_Account")]
        [DevExpress.Xpo.DisplayName(@"Account")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Opening_Balance_account_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please select an account")
]
        public acc_Account account_id
        {
            get { return faccount_id; }
            set { SetPropertyValue<acc_Account>("account_id", ref faccount_id, value); }
        }
        acc_Year fyear_id;
        [Association(@"acc_Opening_BalanceReferencesacc_Year")]
        [DevExpress.Xpo.DisplayName(@"Fiscal Year")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Opening_Balance_year_id_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please select a Fiscal Year")]
        public acc_Year year_id
        {
            get { return fyear_id; }
            set { SetPropertyValue<acc_Year>("year_id", ref fyear_id, value); }
        }
        double fcredit;
        [DevExpress.Xpo.DisplayName(@"Credit")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Opening_Balance_credit_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please Enter a Credit")]
        public double credit
        {
            get { return fcredit; }
            set { SetPropertyValue<double>("credit", ref fcredit, value); }
        }
        double fdebit;
        [DevExpress.Xpo.DisplayName(@"Debit")]
        [DevExpress.Persistent.Validation.RuleRequiredField("acc_Opening_Balance_debit_vld_req", DevExpress.Persistent.Validation.DefaultContexts.Save, "Please select a Debit")]
        public double debit
        {
            get { return fdebit; }
            set { SetPropertyValue<double>("debit", ref fdebit, value); }
        }
    }

}
