//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Accounting.BusinessObjects.Recruitment
{

    [NonPersistent]
    public partial class sp_Income_Statement_fixedResult
    {
        public double Eradat { get; set; }
        public double KhasmMasmohBeeh { get; set; }
        public double EradatMotanaweaa { get; set; }
        public double EradatOmla { get; set; }
        public double TaklefetAshabAamal { get; set; }
        public double TaklefitElEradat { get; set; }
        public double TaklefitOmla { get; set; }
        public double ElmasrofatElomeia { get; set; }
        public double Eihlakat { get; set; }
    }

}
