//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Accounting.BusinessObjects.Recruitment
{

    [NonPersistent]
    public partial class sp_Trial_BalanceResult
    {
        public int Parent_Id { get; set; }
        public string account_name { get; set; }
        public double Entry_debit { get; set; }
        public double Entry_credit { get; set; }
        public double OB_debit { get; set; }
        public double OB_credit { get; set; }
    }

}
