//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment.Web {
    
    
    public partial class index {
        
        /// <summary>
        /// MainPage_Carousel_UC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Recruitment.Web.UC.MainPage_Carousel_UC MainPage_Carousel_UC;
        
        /// <summary>
        /// MainPage_Service_UC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Recruitment.Web.UC.MainPage_Service_UC MainPage_Service_UC;
        
        /// <summary>
        /// MainPage_Project_UC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Recruitment.Web.UC.MainPage_Project_UC MainPage_Project_UC;
        
        /// <summary>
        /// MainPage_Download_UC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Recruitment.Web.UC.MainPage_Download_UC MainPage_Download_UC;
    }
}
