//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Web.BO.Recruitment
{

    public partial class CompanyInfo : XPLiteObject
    {
        string fAboutUs;
        [Size(SizeAttribute.Unlimited)]
        public string AboutUs
        {
            get { return fAboutUs; }
            set { SetPropertyValue<string>("AboutUs", ref fAboutUs, value); }
        }
        int fAutoId;
        [Key(true)]
        public int AutoId
        {
            get { return fAutoId; }
            set { SetPropertyValue<int>("AutoId", ref fAutoId, value); }
        }
        string fCompanyAddress;
        [Size(255)]
        public string CompanyAddress
        {
            get { return fCompanyAddress; }
            set { SetPropertyValue<string>("CompanyAddress", ref fCompanyAddress, value); }
        }
        string fCompanyEmail;
        [Size(255)]
        public string CompanyEmail
        {
            get { return fCompanyEmail; }
            set { SetPropertyValue<string>("CompanyEmail", ref fCompanyEmail, value); }
        }
        string fCompanyMobile1;
        [Size(255)]
        public string CompanyMobile1
        {
            get { return fCompanyMobile1; }
            set { SetPropertyValue<string>("CompanyMobile1", ref fCompanyMobile1, value); }
        }
        string fCompanyMobile2;
        [Size(255)]
        public string CompanyMobile2
        {
            get { return fCompanyMobile2; }
            set { SetPropertyValue<string>("CompanyMobile2", ref fCompanyMobile2, value); }
        }
        string fCompanyName;
        [Size(255)]
        public string CompanyName
        {
            get { return fCompanyName; }
            set { SetPropertyValue<string>("CompanyName", ref fCompanyName, value); }
        }
        string fCompanyPhone1;
        [Size(255)]
        public string CompanyPhone1
        {
            get { return fCompanyPhone1; }
            set { SetPropertyValue<string>("CompanyPhone1", ref fCompanyPhone1, value); }
        }
        string fCompanyPhone2;
        [Size(255)]
        public string CompanyPhone2
        {
            get { return fCompanyPhone2; }
            set { SetPropertyValue<string>("CompanyPhone2", ref fCompanyPhone2, value); }
        }
        string fdribbble;
        [Size(255)]
        public string dribbble
        {
            get { return fdribbble; }
            set { SetPropertyValue<string>("dribbble", ref fdribbble, value); }
        }
        string ffacebook;
        [Size(255)]
        public string facebook
        {
            get { return ffacebook; }
            set { SetPropertyValue<string>("facebook", ref ffacebook, value); }
        }
        string finstagram;
        [Size(255)]
        public string instagram
        {
            get { return finstagram; }
            set { SetPropertyValue<string>("instagram", ref finstagram, value); }
        }
        string flinkedin;
        [Size(255)]
        public string linkedin
        {
            get { return flinkedin; }
            set { SetPropertyValue<string>("linkedin", ref flinkedin, value); }
        }
        string ftwitter;
        [Size(255)]
        public string twitter
        {
            get { return ftwitter; }
            set { SetPropertyValue<string>("twitter", ref ftwitter, value); }
        }
        string fyoutube;
        [Size(255)]
        public string youtube
        {
            get { return fyoutube; }
            set { SetPropertyValue<string>("youtube", ref fyoutube, value); }
        }
    }

}
