//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Web.BO.Recruitment
{

    public partial class Feedback : XPLiteObject
    {
        int fAutoId;
        [Key(true)]
        public int AutoId
        {
            get { return fAutoId; }
            set { SetPropertyValue<int>("AutoId", ref fAutoId, value); }
        }
        DateTime fFeedbackDate;
        public DateTime FeedbackDate
        {
            get { return fFeedbackDate; }
            set { SetPropertyValue<DateTime>("FeedbackDate", ref fFeedbackDate, value); }
        }
        string fFeedbackMail;
        [Size(255)]
        public string FeedbackMail
        {
            get { return fFeedbackMail; }
            set { SetPropertyValue<string>("FeedbackMail", ref fFeedbackMail, value); }
        }
        string fFeedbackMessage;
        [Size(SizeAttribute.Unlimited)]
        public string FeedbackMessage
        {
            get { return fFeedbackMessage; }
            set { SetPropertyValue<string>("FeedbackMessage", ref fFeedbackMessage, value); }
        }
        string fFeedbackName;
        [Size(255)]
        public string FeedbackName
        {
            get { return fFeedbackName; }
            set { SetPropertyValue<string>("FeedbackName", ref fFeedbackName, value); }
        }
    }

}
