//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Web.BO.Recruitment
{

    public partial class Gallary : XPLiteObject
    {
        int fAutoId;
        [Key(true)]
        public int AutoId
        {
            get { return fAutoId; }
            set { SetPropertyValue<int>("AutoId", ref fAutoId, value); }
        }
        string fGallaryName;
        [Size(255)]
        public string GallaryName
        {
            get { return fGallaryName; }
            set { SetPropertyValue<string>("GallaryName", ref fGallaryName, value); }
        }
        string fImageText;
        [Size(255)]
        public string ImageText
        {
            get { return fImageText; }
            set { SetPropertyValue<string>("ImageText", ref fImageText, value); }
        }
        string fImageURL;
        [Size(255)]
        public string ImageURL
        {
            get { return fImageURL; }
            set { SetPropertyValue<string>("ImageURL", ref fImageURL, value); }
        }
    }

}
