//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Web.BO.Recruitment
{

    public partial class rec_job_post : XPLiteObject
    {
        int fjob_post_id;
        [Key(true)]
        public int job_post_id
        {
            get { return fjob_post_id; }
            set { SetPropertyValue<int>("job_post_id", ref fjob_post_id, value); }
        }
        string fjp_content;
        [Size(SizeAttribute.Unlimited)]
        public string jp_content
        {
            get { return fjp_content; }
            set { SetPropertyValue<string>("jp_content", ref fjp_content, value); }
        }
        DateTime fjp_date_end;
        public DateTime jp_date_end
        {
            get { return fjp_date_end; }
            set { SetPropertyValue<DateTime>("jp_date_end", ref fjp_date_end, value); }
        }
        DateTime fjp_date_start;
        public DateTime jp_date_start
        {
            get { return fjp_date_start; }
            set { SetPropertyValue<DateTime>("jp_date_start", ref fjp_date_start, value); }
        }
        byte[] fjp_image;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] jp_image
        {
            get { return fjp_image; }
            set { SetPropertyValue<byte[]>("jp_image", ref fjp_image, value); }
        }
        rec_Industry fjp_industry_id;
        [Association(@"rec_job_postReferencesrec_Industry")]
        public rec_Industry jp_industry_id
        {
            get { return fjp_industry_id; }
            set { SetPropertyValue<rec_Industry>("jp_industry_id", ref fjp_industry_id, value); }
        }
        string fjp_title;
        [Size(150)]
        public string jp_title
        {
            get { return fjp_title; }
            set { SetPropertyValue<string>("jp_title", ref fjp_title, value); }
        }
        int fjp_view_count;
        public int jp_view_count
        {
            get { return fjp_view_count; }
            set { SetPropertyValue<int>("jp_view_count", ref fjp_view_count, value); }
        }
        bool fjp_visible;
        public bool jp_visible
        {
            get { return fjp_visible; }
            set { SetPropertyValue<bool>("jp_visible", ref fjp_visible, value); }
        }
        [Association(@"rec_job_post_applyReferencesrec_job_post")]
        public XPCollection<rec_job_post_apply> rec_job_post_applys { get { return GetCollection<rec_job_post_apply>("rec_job_post_applys"); } }
    }

}
