//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Web.BO.Recruitment
{

    public partial class rec_Applicant : XPLiteObject
    {
        string fapplicant_address;
        [Size(255)]
        public string applicant_address
        {
            get { return fapplicant_address; }
            set { SetPropertyValue<string>("applicant_address", ref fapplicant_address, value); }
        }
        DateTime fapplicant_birth_date;
        public DateTime applicant_birth_date
        {
            get { return fapplicant_birth_date; }
            set { SetPropertyValue<DateTime>("applicant_birth_date", ref fapplicant_birth_date, value); }
        }
        int fapplicant_city_id;
        public int applicant_city_id
        {
            get { return fapplicant_city_id; }
            set { SetPropertyValue<int>("applicant_city_id", ref fapplicant_city_id, value); }
        }
        bool fapplicant_driving_license;
        public bool applicant_driving_license
        {
            get { return fapplicant_driving_license; }
            set { SetPropertyValue<bool>("applicant_driving_license", ref fapplicant_driving_license, value); }
        }
        string fapplicant_email;
        [Size(50)]
        public string applicant_email
        {
            get { return fapplicant_email; }
            set { SetPropertyValue<string>("applicant_email", ref fapplicant_email, value); }
        }
        rec_Gender fapplicant_gender_id;
        [Association(@"rec_ApplicantReferencesrec_Gender")]
        public rec_Gender applicant_gender_id
        {
            get { return fapplicant_gender_id; }
            set { SetPropertyValue<rec_Gender>("applicant_gender_id", ref fapplicant_gender_id, value); }
        }
        int fapplicant_id;
        [Key(true)]
        public int applicant_id
        {
            get { return fapplicant_id; }
            set { SetPropertyValue<int>("applicant_id", ref fapplicant_id, value); }
        }
        int fapplicant_marital_status_id;
        public int applicant_marital_status_id
        {
            get { return fapplicant_marital_status_id; }
            set { SetPropertyValue<int>("applicant_marital_status_id", ref fapplicant_marital_status_id, value); }
        }
        int fapplicant_military_id;
        public int applicant_military_id
        {
            get { return fapplicant_military_id; }
            set { SetPropertyValue<int>("applicant_military_id", ref fapplicant_military_id, value); }
        }
        string fapplicant_mobile;
        [Size(50)]
        public string applicant_mobile
        {
            get { return fapplicant_mobile; }
            set { SetPropertyValue<string>("applicant_mobile", ref fapplicant_mobile, value); }
        }
        string fapplicant_mobile2;
        [Size(50)]
        public string applicant_mobile2
        {
            get { return fapplicant_mobile2; }
            set { SetPropertyValue<string>("applicant_mobile2", ref fapplicant_mobile2, value); }
        }
        string fapplicant_name;
        public string applicant_name
        {
            get { return fapplicant_name; }
            set { SetPropertyValue<string>("applicant_name", ref fapplicant_name, value); }
        }
        string fapplicant_national_id;
        [Size(50)]
        public string applicant_national_id
        {
            get { return fapplicant_national_id; }
            set { SetPropertyValue<string>("applicant_national_id", ref fapplicant_national_id, value); }
        }
        rec_Nationality fapplicant_nationality_id;
        [Association(@"rec_ApplicantReferencesrec_Nationality")]
        public rec_Nationality applicant_nationality_id
        {
            get { return fapplicant_nationality_id; }
            set { SetPropertyValue<rec_Nationality>("applicant_nationality_id", ref fapplicant_nationality_id, value); }
        }
        string fapplicant_phone;
        [Size(50)]
        public string applicant_phone
        {
            get { return fapplicant_phone; }
            set { SetPropertyValue<string>("applicant_phone", ref fapplicant_phone, value); }
        }
        int fapplicant_position_id;
        public int applicant_position_id
        {
            get { return fapplicant_position_id; }
            set { SetPropertyValue<int>("applicant_position_id", ref fapplicant_position_id, value); }
        }
        int fapplicant_rec_applicant_status_id;
        public int applicant_rec_applicant_status_id
        {
            get { return fapplicant_rec_applicant_status_id; }
            set { SetPropertyValue<int>("applicant_rec_applicant_status_id", ref fapplicant_rec_applicant_status_id, value); }
        }
        double fapplicant_salary;
        public double applicant_salary
        {
            get { return fapplicant_salary; }
            set { SetPropertyValue<double>("applicant_salary", ref fapplicant_salary, value); }
        }
        string fapplicant_skill;
        [Size(SizeAttribute.Unlimited)]
        public string applicant_skill
        {
            get { return fapplicant_skill; }
            set { SetPropertyValue<string>("applicant_skill", ref fapplicant_skill, value); }
        }
        string fapplicant_summary;
        [Size(SizeAttribute.Unlimited)]
        public string applicant_summary
        {
            get { return fapplicant_summary; }
            set { SetPropertyValue<string>("applicant_summary", ref fapplicant_summary, value); }
        }
        int fapplicant_work_type_id;
        public int applicant_work_type_id
        {
            get { return fapplicant_work_type_id; }
            set { SetPropertyValue<int>("applicant_work_type_id", ref fapplicant_work_type_id, value); }
        }
        byte[] frec_Applicant_image;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] rec_Applicant_image
        {
            get { return frec_Applicant_image; }
            set { SetPropertyValue<byte[]>("rec_Applicant_image", ref frec_Applicant_image, value); }
        }
        [Association(@"rec_job_post_applyReferencesrec_Applicant")]
        public XPCollection<rec_job_post_apply> rec_job_post_applys { get { return GetCollection<rec_job_post_apply>("rec_job_post_applys"); } }
    }

}
