//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Recruitment.Web.BO.Recruitment
{

    public partial class rec_Industry : XPLiteObject
    {
        int findustry_id;
        [Key(true)]
        public int industry_id
        {
            get { return findustry_id; }
            set { SetPropertyValue<int>("industry_id", ref findustry_id, value); }
        }
        string findustry_name;
        public string industry_name
        {
            get { return findustry_name; }
            set { SetPropertyValue<string>("industry_name", ref findustry_name, value); }
        }
        [Association(@"rec_job_postReferencesrec_Industry")]
        public XPCollection<rec_job_post> rec_job_posts { get { return GetCollection<rec_job_post>("rec_job_posts"); } }
    }

}
